INSERT INTO Companies VALUES (1, '***Capital Changes News')
INSERT INTO Companies VALUES (2, '1st Colonial Bancorp, Inc.')
INSERT INTO Companies VALUES (3, '21C Metals Inc.')
INSERT INTO Companies VALUES (4, '3 Sixty Risk Solutions Ltd.')
INSERT INTO Companies VALUES (5, '360 Blockchain Inc.')
INSERT INTO Companies VALUES (6, '3D Eye Solutions, Inc.')
INSERT INTO Companies VALUES (7, '3D Signatures Inc.')
INSERT INTO Companies VALUES (8, '3Pea International, Inc.')
INSERT INTO Companies VALUES (9, '4 Less Group Inc. (The)')
INSERT INTO Companies VALUES (10, 'A.P. Moller-Maersk A/S')
INSERT INTO Companies VALUES (11, 'AAJ Capital 1 Corp.')
INSERT INTO Companies VALUES (12, 'Abal Group plc')
INSERT INTO Companies VALUES (13, 'Abtech Holdings, Inc.')
INSERT INTO Companies VALUES (14, 'Accell Group')
INSERT INTO Companies VALUES (15, 'Access National Corp.')
INSERT INTO Companies VALUES (16, 'Acreage Holdings, Inc.')
INSERT INTO Companies VALUES (17, 'ACS Actividades de Construccion y Servicios, S.A.')
INSERT INTO Companies VALUES (18, 'Addentax Group Corp.')
INSERT INTO Companies VALUES (19, 'Adevinta ASA')
INSERT INTO Companies VALUES (20, 'Advanced Disposal Services, Inc.')
INSERT INTO Companies VALUES (21, 'Advaxis, Inc. ')
INSERT INTO Companies VALUES (22, 'AdvisorShares Madrona Domestic ETF')
INSERT INTO Companies VALUES (23, 'AdvisorShares Madrona International ETF')
INSERT INTO Companies VALUES (24, 'Adynxx, Inc.')
INSERT INTO Companies VALUES (25, 'Aerkomm Inc.')
INSERT INTO Companies VALUES (26, 'Affinion Group Holdings, Inc.')
INSERT INTO Companies VALUES (27, 'AGC Networks Ltd.')
INSERT INTO Companies VALUES (28, 'Agellan Commercial Real Estate Investment Trust')
INSERT INTO Companies VALUES (29, 'Agritek Holdings, Inc.')
INSERT INTO Companies VALUES (30, 'AGT Food and Ingredients Inc.')
INSERT INTO Companies VALUES (31, 'Aimia Inc.')
INSERT INTO Companies VALUES (32, 'AirMedia Group Inc.')
INSERT INTO Companies VALUES (33, 'AJS Bancorp, Inc. (New)')
INSERT INTO Companies VALUES (34, 'Akbank TAS')
INSERT INTO Companies VALUES (35, 'Akzo Nobel NV')
INSERT INTO Companies VALUES (36, 'Alcon Inc. (2019)')
INSERT INTO Companies VALUES (37, 'Aldershot Resources Ltd.')
INSERT INTO Companies VALUES (38, 'Aldever Resources Inc.')
INSERT INTO Companies VALUES (39, 'Aleafia Health Inc.')
INSERT INTO Companies VALUES (40, 'Alexander & Baldwin, Inc. (New)')
INSERT INTO Companies VALUES (41, 'Alexandria Minerals Corp.')
INSERT INTO Companies VALUES (42, 'Algae Dynamics Corp.')
INSERT INTO Companies VALUES (43, 'Algernon Pharmaceuticals Inc.')
INSERT INTO Companies VALUES (44, 'Algodon Group, Inc.')
INSERT INTO Companies VALUES (45, 'Alignvest Acquisition II Corp.')
INSERT INTO Companies VALUES (46, 'Alkali3 Resources Inc.')
INSERT INTO Companies VALUES (47, 'Alliance California Municipal Income Fund, Inc.')
INSERT INTO Companies VALUES (48, 'Alliance MMA, Inc.')
INSERT INTO Companies VALUES (49, 'Alliqua BioMedical, Inc.')
INSERT INTO Companies VALUES (50, 'Allot Communications Ltd.')
INSERT INTO Companies VALUES (51, 'Allot Ltd.')
INSERT INTO Companies VALUES (52, 'Almirall SA')
INSERT INTO Companies VALUES (53, 'Alpha Real Trust Ltd.')
INSERT INTO Companies VALUES (54, 'Alphacom Holdings, Inc.')
INSERT INTO Companies VALUES (55, 'Alpine Electronics Inc.')
INSERT INTO Companies VALUES (56, 'ALPS ALPINE CO. LTD.')
INSERT INTO Companies VALUES (57, 'Alps Electric Co. Ltd.')
INSERT INTO Companies VALUES (58, 'ALQ Gold Corp.')
INSERT INTO Companies VALUES (59, 'Altan Nevada Minerals Ltd.')
INSERT INTO Companies VALUES (60, 'AltaPacific Bancorp')
INSERT INTO Companies VALUES (61, 'Alterity Therapeutics Ltd.')
INSERT INTO Companies VALUES (62, 'Altice Europe N.V.')
INSERT INTO Companies VALUES (63, 'Altitude Resources, Inc.')
INSERT INTO Companies VALUES (64, 'Amber Road, Inc.')
INSERT INTO Companies VALUES (65, 'Amcor Ltd.')
INSERT INTO Companies VALUES (66, 'Amer Sports Corp.')
INSERT INTO Companies VALUES (67, 'American Airlines Group Inc.')
INSERT INTO Companies VALUES (68, 'American Battery Metals Corp.')
INSERT INTO Companies VALUES (69, 'American Battery Metals Corp. (NV)')
INSERT INTO Companies VALUES (70, 'American BriVision (Holding) Corp.')
INSERT INTO Companies VALUES (71, 'American Hemp Ventures Inc.')
INSERT INTO Companies VALUES (72, 'American Midstream Partners, LP')
INSERT INTO Companies VALUES (73, 'American National Bankshares Inc.')
INSERT INTO Companies VALUES (74, 'Americas Silver Corp.')
INSERT INTO Companies VALUES (75, 'AmeriGas Partners, L.P.')
INSERT INTO Companies VALUES (76, 'Amilot Capital Inc.')
INSERT INTO Companies VALUES (77, 'Amplify Energy Corp.')
INSERT INTO Companies VALUES (78, 'AmpliPhi Biosciences Corp.')
INSERT INTO Companies VALUES (79, 'Anadarko Petroleum Corp.')
INSERT INTO Companies VALUES (80, 'Andeavor Logistics LP')
INSERT INTO Companies VALUES (81, 'Andover National Corp.')
INSERT INTO Companies VALUES (82, 'Annaly Capital Management, Inc.')
INSERT INTO Companies VALUES (83, 'Antero Midstream Corp.')
INSERT INTO Companies VALUES (84, 'Antero Midstream GP LP')
INSERT INTO Companies VALUES (85, 'Antero Midstream Partners LP')
INSERT INTO Companies VALUES (86, 'Apartment Investment and Management Co.')
INSERT INTO Companies VALUES (87, 'Aphria Inc.')
INSERT INTO Companies VALUES (88, 'Apollo Global Management, LLC')
INSERT INTO Companies VALUES (89, 'Appalachian Mountain Brewery, Inc.')
INSERT INTO Companies VALUES (90, 'Appliance Recycling Centers of America, Inc. (NV)')
INSERT INTO Companies VALUES (91, 'Apptio, Inc.')
INSERT INTO Companies VALUES (92, 'APPx Group Holdings Inc.')
INSERT INTO Companies VALUES (93, 'Apricus Biosciences, Inc.')
INSERT INTO Companies VALUES (94, 'Aptitude Software Group plc')
INSERT INTO Companies VALUES (95, 'Aquantia Corp.')
INSERT INTO Companies VALUES (96, 'Aratana Therapeutics, Inc.')
INSERT INTO Companies VALUES (97, 'Arbor Realty Trust, Inc.')
INSERT INTO Companies VALUES (98, 'ARCA biopharma Inc.')
INSERT INTO Companies VALUES (99, 'Arcom')
INSERT INTO Companies VALUES (100, 'Arcturus Therapeutics Ltd.')
INSERT INTO Companies VALUES (101, 'Arcwest Exploration Inc.')
INSERT INTO Companies VALUES (102, 'Arlo Technologies, Inc.')
INSERT INTO Companies VALUES (103, 'Armata Pharmaceuticals, Inc.')
INSERT INTO Companies VALUES (104, 'Arris International plc')
INSERT INTO Companies VALUES (105, 'Arsanis, Inc.')
INSERT INTO Companies VALUES (106, 'ASC Biosciences, Inc. ')
INSERT INTO Companies VALUES (107, 'Ascot Resources Ltd. ')
INSERT INTO Companies VALUES (108, 'Ashanti Gold Corp.')
INSERT INTO Companies VALUES (109, 'Asia Pacific Fund, Inc. (The)')
INSERT INTO Companies VALUES (110, 'Aspen Insurance Holdings Ltd.')
INSERT INTO Companies VALUES (111, 'Assura plc')
INSERT INTO Companies VALUES (112, 'Asterias Biotherapeutics, Inc.')
INSERT INTO Companies VALUES (113, 'AT&T Inc.')
INSERT INTO Companies VALUES (114, 'ATEX Resources Inc.')
INSERT INTO Companies VALUES (115, 'athenahealth, Inc.')
INSERT INTO Companies VALUES (116, 'Atlantic Gold Corp.')
INSERT INTO Companies VALUES (117, 'Atlantic Union Bankshares Corp.')
INSERT INTO Companies VALUES (118, 'Atos SE')
INSERT INTO Companies VALUES (119, 'Attis Industries, Inc. ')
INSERT INTO Companies VALUES (120, 'Attunity Ltd.')
INSERT INTO Companies VALUES (121, 'Aura Energy, Inc.')
INSERT INTO Companies VALUES (122, 'Aura Minerals Inc. (BVI)')
INSERT INTO Companies VALUES (123, 'Auralite Investments Inc.')
INSERT INTO Companies VALUES (124, 'Aurex Energy Corp.')
INSERT INTO Companies VALUES (125, 'Auris Medical Holding AG (New)')
INSERT INTO Companies VALUES (126, 'Auris Medical Holding Ltd. (Bermuda)')
INSERT INTO Companies VALUES (127, 'Avidian Gold Corp.')
INSERT INTO Companies VALUES (128, 'Avista Corp.')
INSERT INTO Companies VALUES (129, 'Avon Products, Inc.')
INSERT INTO Companies VALUES (130, 'Axovant Gene Therapies Ltd.')
INSERT INTO Companies VALUES (131, 'Axovant Sciences Ltd.')
INSERT INTO Companies VALUES (132, 'AYR Strategies Inc.')
INSERT INTO Companies VALUES (133, 'Banco Bradesco SA')
INSERT INTO Companies VALUES (134, 'Banco Santander Mexico, S.A., Institucion de Banca Multiple, Grupo Financiero Santander Mexico')
INSERT INTO Companies VALUES (135, 'Bank of East Asia Ltd.')
INSERT INTO Companies VALUES (136, 'Bank of Nova Scotia')
INSERT INTO Companies VALUES (137, 'Bantek, Inc.')
INSERT INTO Companies VALUES (138, 'Barclays PLC')
INSERT INTO Companies VALUES (139, 'Bard Ventures Ltd.')
INSERT INTO Companies VALUES (140, 'Barrick Gold Corp.')
INSERT INTO Companies VALUES (141, 'Bat Group, Inc.')
INSERT INTO Companies VALUES (142, 'BayCom Corp.')
INSERT INTO Companies VALUES (143, 'Bayside Corp.')
INSERT INTO Companies VALUES (144, 'Beeston Enterprises, Ltd.')
INSERT INTO Companies VALUES (145, 'Bellatrix Exploration Ltd.')
INSERT INTO Companies VALUES (146, 'Belmond Ltd.')
INSERT INTO Companies VALUES (147, 'Bemis Co., Inc.')
INSERT INTO Companies VALUES (148, 'Beneficial Bancorp, Inc.')
INSERT INTO Companies VALUES (149, 'Berkley (W. R.) Corp.')
INSERT INTO Companies VALUES (150, 'Berkshire Hills Bancorp, Inc.')
INSERT INTO Companies VALUES (151, 'Best of the Best plc')
INSERT INTO Companies VALUES (152, 'BestnPet, Inc.')
INSERT INTO Companies VALUES (153, 'BetaPro Natural Gas 2x Daily Bull ETF')
INSERT INTO Companies VALUES (154, 'BetaPro S&P 500 -2x Daily Bear ETF')
INSERT INTO Companies VALUES (155, 'Better Choice Company Inc.')
INSERT INTO Companies VALUES (156, 'Between Dandelions, Inc.')
INSERT INTO Companies VALUES (157, 'Bevo Agro Inc.')
INSERT INTO Companies VALUES (158, 'BFE Corp.')
INSERT INTO Companies VALUES (159, 'BGC Partners, Inc.')
INSERT INTO Companies VALUES (160, 'Bioblast Pharma Ltd.')
INSERT INTO Companies VALUES (161, 'Bioceres Crop Solutions Corp.')
INSERT INTO Companies VALUES (162, 'BioCorRx Inc.')
INSERT INTO Companies VALUES (163, 'Biologix Hair, Inc.')
INSERT INTO Companies VALUES (164, 'BioMimetic Therapeutics, Inc.')
INSERT INTO Companies VALUES (165, 'Bio-Path Holdings, Inc. (DE)')
INSERT INTO Companies VALUES (166, 'BioPharmX Corp.')
INSERT INTO Companies VALUES (167, 'Bioquell plc')
INSERT INTO Companies VALUES (168, 'Bioscience Neutraceuticals, Inc.')
INSERT INTO Companies VALUES (169, 'BioTime Inc.')
INSERT INTO Companies VALUES (170, 'BIQI International Holdings Corp.')
INSERT INTO Companies VALUES (171, 'Birner Dental Management Services, Inc.')
INSERT INTO Companies VALUES (172, 'Bison Capital Acquisition Corp.')
INSERT INTO Companies VALUES (173, 'Bitcoin Generation, Inc.')
INSERT INTO Companies VALUES (174, 'Bitcoin Investment Trust')
INSERT INTO Companies VALUES (175, 'BK Technologies Corp.')
INSERT INTO Companies VALUES (176, 'BK Technologies, Inc.')
INSERT INTO Companies VALUES (177, 'Black Box Corp.')
INSERT INTO Companies VALUES (178, 'Black Sea Copper & Gold Corp.')
INSERT INTO Companies VALUES (179, 'Blackbird Energy Inc.')
INSERT INTO Companies VALUES (180, 'BlackPearl Resources Inc. ')
INSERT INTO Companies VALUES (181, 'BlackRock California Municipal 2018 Term Trust')
INSERT INTO Companies VALUES (182, 'BlackRock Debt Strategies Fund, Inc.')
INSERT INTO Companies VALUES (183, 'BlackRock Municipal 2018 Term Trust')
INSERT INTO Companies VALUES (184, 'BlackRock New York Municipal 2018 Term Trust')
INSERT INTO Companies VALUES (185, 'BlockMint Technologies Inc.')
INSERT INTO Companies VALUES (186, 'Blue Hills Bancorp, Inc.')
INSERT INTO Companies VALUES (187, 'Blue Ridge Mountain Resources, Inc.')
INSERT INTO Companies VALUES (188, 'Blue Star Gold Corp.')
INSERT INTO Companies VALUES (189, 'Blue Valley Ban Corp.')
INSERT INTO Companies VALUES (190, 'Blueberries Medical Corp.')
INSERT INTO Companies VALUES (191, 'Blvd Centers Corp.')
INSERT INTO Companies VALUES (192, 'BMO Equal Weight Global Base Metals Hedged to CAD Index ETF')
INSERT INTO Companies VALUES (193, 'BMO Equal Weight Global Gold Index ETF')
INSERT INTO Companies VALUES (194, 'BMO Equal Weight Oil & Gas Index ETF')
INSERT INTO Companies VALUES (195, 'BMO Junior Gas Index ETF')
INSERT INTO Companies VALUES (196, 'BMO Junior Gold Index ETF')
INSERT INTO Companies VALUES (197, 'BMO Junior Oil Index ETF ')
INSERT INTO Companies VALUES (198, 'Body Basics, Inc.')
INSERT INTO Companies VALUES (199, 'Bojangles'', Inc.')
INSERT INTO Companies VALUES (200, 'Boliden AB')
INSERT INTO Companies VALUES (201, 'Bonmarche Holdings plc')
INSERT INTO Companies VALUES (202, 'Boxhill Technologies plc')
INSERT INTO Companies VALUES (203, 'BP plc')
INSERT INTO Companies VALUES (204, 'BQE Water Inc.')
INSERT INTO Companies VALUES (205, 'Bravatek Solutions, Inc.')
INSERT INTO Companies VALUES (206, 'Breathtec BioMedical, Inc.')
INSERT INTO Companies VALUES (207, 'Bridgeline Digital, Inc.')
INSERT INTO Companies VALUES (208, 'Bridgepoint Education, Inc.')
INSERT INTO Companies VALUES (209, 'Brompton European Dividend Growth ETF')
INSERT INTO Companies VALUES (210, 'Brompton Global Healthcare Income and Growth ETF')
INSERT INTO Companies VALUES (211, 'Brompton Tech Leaders Income ETF')
INSERT INTO Companies VALUES (212, 'Brookfield Business Partners L.P.')
INSERT INTO Companies VALUES (213, 'Brookfield Property Partners L.P.')
INSERT INTO Companies VALUES (214, 'Brookfield Property REIT Inc.')
INSERT INTO Companies VALUES (215, 'Brunswick Corp.')
INSERT INTO Companies VALUES (216, 'BSB Bancorp, Inc. (MA)')
INSERT INTO Companies VALUES (217, 'BSM Technologies Inc.')
INSERT INTO Companies VALUES (218, 'BTCS Inc.')
INSERT INTO Companies VALUES (219, 'BTG plc')
INSERT INTO Companies VALUES (220, 'BTL Group Ltd.')
INSERT INTO Companies VALUES (221, 'Buckeye Partners, L.P.')
INSERT INTO Companies VALUES (222, 'Bullzi Holdings, Inc.')
INSERT INTO Companies VALUES (223, 'Bunker Hill Mining Corp.')
INSERT INTO Companies VALUES (224, 'Burcon NutraScience Corp.')
INSERT INTO Companies VALUES (225, 'BUZZ US Sentiment Leaders ETF')
INSERT INTO Companies VALUES (226, 'CAB Financial Corp.')
INSERT INTO Companies VALUES (227, 'Cadence Bancorporation')
INSERT INTO Companies VALUES (228, 'CalEthos, Inc.')
INSERT INTO Companies VALUES (229, 'Canaccord Genuity Growth Corp.')
INSERT INTO Companies VALUES (230, 'Canada Cobalt Works Inc.')
INSERT INTO Companies VALUES (231, 'Canadian Imperial Bank of Commerce (Toronto, Canada)')
INSERT INTO Companies VALUES (232, 'Canadian Platinum Corp.')
INSERT INTO Companies VALUES (233, 'CanaQuest Medical Corp.')
INSERT INTO Companies VALUES (234, 'CanAsia Financial Inc.')
INSERT INTO Companies VALUES (235, 'Can-Fite Biopharma Ltd.')
INSERT INTO Companies VALUES (236, 'Cang Bao Tian Xia International Art Trade Center, Inc.')
INSERT INTO Companies VALUES (237, 'Cannabis One Holdings Inc.')
INSERT INTO Companies VALUES (238, 'Cannabis Strategies Acquisition Corp.')
INSERT INTO Companies VALUES (239, 'Cannabis Suisse Corp.')
INSERT INTO Companies VALUES (240, 'Cannagistics Inc.')
INSERT INTO Companies VALUES (241, 'CannaRoyalty Corp.')
INSERT INTO Companies VALUES (242, 'Cannex Capital Holdings Inc.')
INSERT INTO Companies VALUES (243, 'Capital & Counties Properties plc')
INSERT INTO Companies VALUES (244, 'Capital Bank of New Jersey')
INSERT INTO Companies VALUES (245, 'Capital Product Partners L.P.')
INSERT INTO Companies VALUES (246, 'Capitol Investment Corp. IV')
INSERT INTO Companies VALUES (247, 'Capri Holdings Ltd.')
INSERT INTO Companies VALUES (248, 'Cardiff Lexington Corp.')
INSERT INTO Companies VALUES (249, 'Carroll Bancorp, Inc.')
INSERT INTO Companies VALUES (250, 'Carrols Restaurant Group, Inc.')
INSERT INTO Companies VALUES (251, 'Carrols Restaurant Group, Inc. (New)')
INSERT INTO Companies VALUES (252, 'CAS Medical Systems, Inc.')
INSERT INTO Companies VALUES (253, 'Cassava Sciences, Inc.')
INSERT INTO Companies VALUES (254, 'CAT Strategic Metals Corp.')
INSERT INTO Companies VALUES (255, 'CBD Life Sciences Inc.')
INSERT INTO Companies VALUES (256, 'cbdMD, Inc.')
INSERT INTO Companies VALUES (257, 'Cdn MSolar Corp.')
INSERT INTO Companies VALUES (258, 'Cecil Bancorp, Inc. (New)')
INSERT INTO Companies VALUES (259, 'Celexus, Inc.')
INSERT INTO Companies VALUES (260, 'Celgene Corp.')
INSERT INTO Companies VALUES (261, 'Celldex Therapeutics, Inc.')
INSERT INTO Companies VALUES (262, 'Cellnex Telecom, S.A.')
INSERT INTO Companies VALUES (263, 'Cemtrex, Inc.')
INSERT INTO Companies VALUES (264, 'Centene Corp.')
INSERT INTO Companies VALUES (265, 'CenterPoint Energy, Inc.')
INSERT INTO Companies VALUES (266, 'CenterState Bank Corp.')
INSERT INTO Companies VALUES (267, 'CENTR Brands Corp.')
INSERT INTO Companies VALUES (268, 'CGI Group, Inc.')
INSERT INTO Companies VALUES (269, 'CGI Inc.')
INSERT INTO Companies VALUES (270, 'CGX Energy Inc.')
INSERT INTO Companies VALUES (271, 'CH Bailey Plc')
INSERT INTO Companies VALUES (272, 'Changming Industrial Management Group Holding')
INSERT INTO Companies VALUES (273, 'Chanticleer Holdings, Inc.')
INSERT INTO Companies VALUES (274, 'Chesapeake Energy Corp.')
INSERT INTO Companies VALUES (275, 'Chesapeake Lodging Trust')
INSERT INTO Companies VALUES (276, 'CHF Solutions, Inc.')
INSERT INTO Companies VALUES (277, 'Chimata Gold Corp.')
INSERT INTO Companies VALUES (278, 'China Commercial Credit, Inc.')
INSERT INTO Companies VALUES (279, 'China Foods Holdings Ltd.')
INSERT INTO Companies VALUES (280, 'China Fund, Inc. (The)')
INSERT INTO Companies VALUES (281, 'China Health Care Corp.')
INSERT INTO Companies VALUES (282, 'ChipMOS TECHNOLOGIES INC.')
INSERT INTO Companies VALUES (283, 'Chr. Hansen Holding A/S')
INSERT INTO Companies VALUES (284, 'Churchill Capital Corp.')
INSERT INTO Companies VALUES (285, 'Cimarex Energy Co.')
INSERT INTO Companies VALUES (286, 'Cinaport Acquisition Corp. II')
INSERT INTO Companies VALUES (287, 'CIS Acquisition Ltd.')
INSERT INTO Companies VALUES (288, 'Citigroup Inc.')
INSERT INTO Companies VALUES (289, 'Citizens First Corp.')
INSERT INTO Companies VALUES (290, 'Citizens Independent Bancorp, Inc.')
INSERT INTO Companies VALUES (291, 'City View Green Holdings Inc.')
INSERT INTO Companies VALUES (292, 'Civitas Solutions, Inc.')
INSERT INTO Companies VALUES (293, 'Clarivate Analytics plc')
INSERT INTO Companies VALUES (294, 'Clatsop Community Bank')
INSERT INTO Companies VALUES (295, 'Clear Channel Outdoor Holdings, Inc.')
INSERT INTO Companies VALUES (296, 'Clear Channel Outdoor Holdings, Inc. (New)')
INSERT INTO Companies VALUES (297, 'Clementia Pharmaceuticals Inc.')
INSERT INTO Companies VALUES (298, 'Cliffside Capital Ltd.')
INSERT INTO Companies VALUES (299, 'Cloud Nine Education Group Ltd.')
INSERT INTO Companies VALUES (300, 'Cloudera, Inc.')
INSERT INTO Companies VALUES (301, 'CM Seven Star Acquisition Corp.')
INSERT INTO Companies VALUES (302, 'Coastal Carolina Bancshares, Inc.')
INSERT INTO Companies VALUES (303, 'Cobalt Power Group Inc.')
INSERT INTO Companies VALUES (304, 'CoBiz Financial Inc.')
INSERT INTO Companies VALUES (305, 'Coca-Cola Bottling Co. Consolidated')
INSERT INTO Companies VALUES (306, 'Coca-Cola Consolidated, Inc.')
INSERT INTO Companies VALUES (307, 'Coca-Cola FEMSA SAB de CV')
INSERT INTO Companies VALUES (308, 'Codebase Ventures Inc.')
INSERT INTO Companies VALUES (309, 'Cohen & Steers REIT and Preferred and Income Fund, Inc.')
INSERT INTO Companies VALUES (310, 'Cohen & Steers REIT and Preferred Income Fund, Inc.')
INSERT INTO Companies VALUES (311, 'Colefax Group plc')
INSERT INTO Companies VALUES (312, 'Colombia Crest Gold Corp.')
INSERT INTO Companies VALUES (313, 'Columbia Care Inc.')
INSERT INTO Companies VALUES (314, 'Com Hem Holding AB')
INSERT INTO Companies VALUES (315, 'Command Security Corp.')
INSERT INTO Companies VALUES (316, 'Commencement Bank')
INSERT INTO Companies VALUES (317, 'Commercial International Bank Egypt SAE')
INSERT INTO Companies VALUES (318, 'CommScope Holding Co., Inc.')
INSERT INTO Companies VALUES (319, 'Community 1st Bank (Idaho)')
INSERT INTO Companies VALUES (320, 'Community Financial Group, Inc. (Wash.)')
INSERT INTO Companies VALUES (321, 'Composite Alliance Group Inc.')
INSERT INTO Companies VALUES (322, 'Computer Services, Inc. (Ky.)')
INSERT INTO Companies VALUES (323, 'Concrete Pumping Holdings, Inc.')
INSERT INTO Companies VALUES (324, 'Connecticut Water Service, Inc.')
INSERT INTO Companies VALUES (325, 'ConnectOne Bancorp, Inc. (New)')
INSERT INTO Companies VALUES (326, 'Control4 Corp.')
INSERT INTO Companies VALUES (327, 'Convatec Group plc')
INSERT INTO Companies VALUES (328, 'ConvergeOne Holdings, Inc.')
INSERT INTO Companies VALUES (329, 'Core Gold Inc.')
INSERT INTO Companies VALUES (330, 'CorMedix Inc.')
INSERT INTO Companies VALUES (331, 'Cornerstone Building Brands, Inc.')
INSERT INTO Companies VALUES (332, 'Cortex Business Solutions Inc.')
INSERT INTO Companies VALUES (333, 'Cosan Ltd.')
INSERT INTO Companies VALUES (334, 'Costain Group PLC')
INSERT INTO Companies VALUES (335, 'Coty, Inc. (New)')
INSERT INTO Companies VALUES (336, 'Covetrus, Inc.')
INSERT INTO Companies VALUES (337, 'Cranswick plc')
INSERT INTO Companies VALUES (338, 'Crawford United Corp.')
INSERT INTO Companies VALUES (339, 'Cray Inc.')
INSERT INTO Companies VALUES (340, 'Cresval Capital Corp.')
INSERT INTO Companies VALUES (341, 'Critical Control Energy Services Corp.')
INSERT INTO Companies VALUES (342, 'Crius Energy Trust')
INSERT INTO Companies VALUES (343, 'Croda International plc')
INSERT INTO Companies VALUES (344, 'Cruzani, Inc.')
INSERT INTO Companies VALUES (345, 'Cryptobloc Technologies Corp.')
INSERT INTO Companies VALUES (346, 'CVR Refining, LP')
INSERT INTO Companies VALUES (347, 'Cyber Apps World Inc.')
INSERT INTO Companies VALUES (348, 'Cyclerion Therapeutics, Inc.')
INSERT INTO Companies VALUES (349, 'Cypherpunk Holdings Inc.')
INSERT INTO Companies VALUES (350, 'Daily Mail & General Trust plc')
INSERT INTO Companies VALUES (351, 'Dairy Crest Group plc')
INSERT INTO Companies VALUES (352, 'Dais Analytic Corp.')
INSERT INTO Companies VALUES (353, 'Dais Corp.')
INSERT INTO Companies VALUES (354, 'Danaos Corp.')
INSERT INTO Companies VALUES (355, 'Darien Business Development Corp.')
INSERT INTO Companies VALUES (356, 'Declan Cobalt Inc.')
INSERT INTO Companies VALUES (357, 'Defiance Silver Corp.')
INSERT INTO Companies VALUES (358, 'Delivra Corp.')
INSERT INTO Companies VALUES (359, 'Dell Technologies Inc.')
INSERT INTO Companies VALUES (360, 'DelMar Pharmaceuticals, Inc.')
INSERT INTO Companies VALUES (361, 'Delta Technology Holdings Ltd.')
INSERT INTO Companies VALUES (362, 'Demant A/S')
INSERT INTO Companies VALUES (363, 'Desert Lion Energy Inc.')
INSERT INTO Companies VALUES (364, 'Designer Brands Inc.')
INSERT INTO Companies VALUES (365, 'DevMar Equities, Inc.')
INSERT INTO Companies VALUES (366, 'Diamond Hill Valuation-Weighted 500 ETF')
INSERT INTO Companies VALUES (367, 'Diamond S Shipping Inc.')
INSERT INTO Companies VALUES (368, 'Diana Containerships Inc.')
INSERT INTO Companies VALUES (369, 'Diana Shipping Inc.')
INSERT INTO Companies VALUES (370, 'Digital Realty Trust Inc.')
INSERT INTO Companies VALUES (371, 'Digitalbox plc')
INSERT INTO Companies VALUES (372, 'Disney (Walt) Company (2019) (The)')
INSERT INTO Companies VALUES (373, 'Disney (Walt) Company (New) (The)')
INSERT INTO Companies VALUES (374, 'Dominion Energy Midstream Partners, LP')
INSERT INTO Companies VALUES (375, 'Dominion Energy, Inc.')
INSERT INTO Companies VALUES (376, 'Don Quijote Holdings Co. Ltd.')
INSERT INTO Companies VALUES (377, 'Dover Downs Gaming & Entertainment, Inc.')
INSERT INTO Companies VALUES (378, 'Dow Inc.')
INSERT INTO Companies VALUES (379, 'DPW Holdings, Inc.')
INSERT INTO Companies VALUES (380, 'Draper Oakwood Technology Acquisition, Inc.')
INSERT INTO Companies VALUES (381, 'Drilling Company of 1972 A/S (The)')
INSERT INTO Companies VALUES (382, 'Driven Deliveries, Inc. ')
INSERT INTO Companies VALUES (383, 'Drone USA, Inc.')
INSERT INTO Companies VALUES (384, 'DropCar, Inc.')
INSERT INTO Companies VALUES (385, 'DSG Global Inc. ')
INSERT INTO Companies VALUES (386, 'DSW Inc.')
INSERT INTO Companies VALUES (387, 'Duckworth Capital Corp.')
INSERT INTO Companies VALUES (388, 'DuluxGroup Ltd.')
INSERT INTO Companies VALUES (389, 'Dun & Bradstreet Corp. (2000)')
INSERT INTO Companies VALUES (390, 'Duncan Park Holdings Corp.')
INSERT INTO Companies VALUES (391, 'Dundee Corp.')
INSERT INTO Companies VALUES (392, 'DuPont de Nemours, Inc.')
INSERT INTO Companies VALUES (393, 'Dynex Power Inc.')
INSERT INTO Companies VALUES (394, 'EA Education Group Inc.')
INSERT INTO Companies VALUES (395, 'Eagle Materials Inc.')
INSERT INTO Companies VALUES (396, 'Eagle Oil Holding Company, Inc.')
INSERT INTO Companies VALUES (397, 'Earny Resources Ltd.')
INSERT INTO Companies VALUES (398, 'Earthport plc')
INSERT INTO Companies VALUES (399, 'EarthRenew Inc.')
INSERT INTO Companies VALUES (400, 'Eaton Vance Massachusetts Municipal Income Trust')
INSERT INTO Companies VALUES (401, 'Eaton Vance Municipal Bond Fund')
INSERT INTO Companies VALUES (402, 'Eaton Vance Municipal Bond Fund II')
INSERT INTO Companies VALUES (403, 'Eaton Vance Municipal Income Trust')
INSERT INTO Companies VALUES (404, 'Eaton Vance New Jersey Municipal Bond Fund')
INSERT INTO Companies VALUES (405, 'Eaton Vance New Jersey Municipal Income Trust')
INSERT INTO Companies VALUES (406, 'Eaton Vance Ohio Municipal Bond Fund ')
INSERT INTO Companies VALUES (407, 'Eaton Vance Ohio Municipal Income Trust')
INSERT INTO Companies VALUES (408, 'Eaton Vance Pennsylvania Municipal Bond Fund')
INSERT INTO Companies VALUES (409, 'Eaton Vance Pennsylvania Municipal Income Trust')
INSERT INTO Companies VALUES (410, 'Eaton Vance Tax-Advantaged Bond and Option Strategies Fund')
INSERT INTO Companies VALUES (411, 'Eaton Vance Tax-Managed Buy-Write Strategy Fund')
INSERT INTO Companies VALUES (412, 'EchoStar Corp.')
INSERT INTO Companies VALUES (413, 'Eclipse Resources Corp.')
INSERT INTO Companies VALUES (414, 'ECN Capital Corp.')
INSERT INTO Companies VALUES (415, 'Eco Tek 360, Inc.')
INSERT INTO Companies VALUES (416, 'eCobalt Solutions Inc.')
INSERT INTO Companies VALUES (417, 'Ecolab Inc.')
INSERT INTO Companies VALUES (418, 'Eco-Stim Energy Solutions, Inc.')
INSERT INTO Companies VALUES (419, 'Edgar Express, Inc.')
INSERT INTO Companies VALUES (420, 'Edge Therapeutics, Inc.')
INSERT INTO Companies VALUES (421, 'Edwards Lifesciences Corp.')
INSERT INTO Companies VALUES (422, 'eHi Car Services Ltd.')
INSERT INTO Companies VALUES (423, 'Elanco Animal Health Inc.')
INSERT INTO Companies VALUES (424, 'Elecosoft plc')
INSERT INTO Companies VALUES (425, 'Electro Scientific Industries, Inc.')
INSERT INTO Companies VALUES (426, 'Electrolux AB')
INSERT INTO Companies VALUES (427, 'Electronics for Imaging, Inc.')
INSERT INTO Companies VALUES (428, 'Element Solutions Inc.')
INSERT INTO Companies VALUES (429, 'Ellie Mae, Inc.')
INSERT INTO Companies VALUES (430, 'Ellington Financial Inc.')
INSERT INTO Companies VALUES (431, 'Ellington Financial LLC')
INSERT INTO Companies VALUES (432, 'Eltek Ltd.')
INSERT INTO Companies VALUES (433, 'Emblem Corp.')
INSERT INTO Companies VALUES (434, 'EMC Insurance Group Inc.')
INSERT INTO Companies VALUES (435, 'Emerald Bioscience, Inc.')
INSERT INTO Companies VALUES (436, 'Enbridge Energy Partners, L.P.')
INSERT INTO Companies VALUES (437, 'Enbridge Income Fund Holdings Inc.')
INSERT INTO Companies VALUES (438, 'EnCana Corp.')
INSERT INTO Companies VALUES (439, 'Endologix, Inc.')
INSERT INTO Companies VALUES (440, 'Engex, Inc.')
INSERT INTO Companies VALUES (441, 'Enghouse Systems Ltd.')
INSERT INTO Companies VALUES (442, 'Engility Holdings, Inc. (New)')
INSERT INTO Companies VALUES (443, 'EnLink Midstream Partners, LP')
INSERT INTO Companies VALUES (444, 'Enlink Midstream, LLC')
INSERT INTO Companies VALUES (445, 'Enlivex Therapeutics Ltd.')
INSERT INTO Companies VALUES (446, 'Ensco plc')
INSERT INTO Companies VALUES (447, 'Ensco Rowan plc')
INSERT INTO Companies VALUES (448, 'Ensign Group, Inc. (The)')
INSERT INTO Companies VALUES (449, 'Entegra Financial Corp.')
INSERT INTO Companies VALUES (450, 'Enterprise Financial Services Corp')
INSERT INTO Companies VALUES (451, 'Enthusiast Gaming Holdings Inc.')
INSERT INTO Companies VALUES (452, 'Enviro-Serv, Inc.')
INSERT INTO Companies VALUES (453, 'Envision Solar International, Inc.')
INSERT INTO Companies VALUES (454, 'Epic Corp. (CO)')
INSERT INTO Companies VALUES (455, 'EQGP Holdings, LP')
INSERT INTO Companies VALUES (456, 'Espial Group Inc.')
INSERT INTO Companies VALUES (457, 'Essendant Inc.')
INSERT INTO Companies VALUES (458, 'Esterline Technologies Corp.')
INSERT INTO Companies VALUES (459, 'Ethereum Classic Investment Trust')
INSERT INTO Companies VALUES (460, 'Eurocastle Investment Ltd.')
INSERT INTO Companies VALUES (461, 'Euromoney Institutional Investor plc')
INSERT INTO Companies VALUES (462, 'European Commercial Real Estate Investment Trust')
INSERT INTO Companies VALUES (463, 'European Dividend Growth Fund')
INSERT INTO Companies VALUES (464, 'European Residential Real Estate Investment Trust')
INSERT INTO Companies VALUES (465, 'Eurotin Inc.')
INSERT INTO Companies VALUES (466, 'EVI Global Group Developments Corp.')
INSERT INTO Companies VALUES (467, 'Exactus, Inc.')
INSERT INTO Companies VALUES (468, 'EXMceuticals Inc.')
INSERT INTO Companies VALUES (469, 'Express Scripts Holding Co.')
INSERT INTO Companies VALUES (470, 'FamilyMart UNY Holdings Co., Ltd.')
INSERT INTO Companies VALUES (471, 'Fang Holdings Ltd.')
INSERT INTO Companies VALUES (472, 'Faroe Petroleum plc')
INSERT INTO Companies VALUES (473, 'Fast Lane Holdings, Inc.')
INSERT INTO Companies VALUES (474, 'Fastenal Co.')
INSERT INTO Companies VALUES (475, 'FAT Brands Inc.')
INSERT INTO Companies VALUES (476, 'Favo Realty, Inc.')
INSERT INTO Companies VALUES (477, 'FAX Capital Corp.')
INSERT INTO Companies VALUES (478, 'FC Global Realty Inc.')
INSERT INTO Companies VALUES (479, 'FCB Financial Holdings, Inc.')
INSERT INTO Companies VALUES (480, 'Federal Street Acquisition Corp.')
INSERT INTO Companies VALUES (481, 'Ferguson plc')
INSERT INTO Companies VALUES (482, 'Ferguson plc (New)')
INSERT INTO Companies VALUES (483, 'Ferrovial SA')
INSERT INTO Companies VALUES (484, 'Fibria Celulose SA')
INSERT INTO Companies VALUES (485, 'Fidelity Minerals Corp.')
INSERT INTO Companies VALUES (486, 'Fidelity Southern Corporation')
INSERT INTO Companies VALUES (487, 'Fifth Street Asset Management Inc.')
INSERT INTO Companies VALUES (488, 'Fifth Third Bancorp (Cincinnati, Ohio)')
INSERT INTO Companies VALUES (489, 'Findel plc')
INSERT INTO Companies VALUES (490, 'Finisar Corp.')
INSERT INTO Companies VALUES (491, 'Fire & Flower Holdings Corp.')
INSERT INTO Companies VALUES (492, 'Fireswirl Technologies Inc.')
INSERT INTO Companies VALUES (493, 'First Bancshares, Inc. (MS) (The)')
INSERT INTO Companies VALUES (494, 'First Bauxite Corp. ')
INSERT INTO Companies VALUES (495, 'First Citizens BancShares, Inc.')
INSERT INTO Companies VALUES (496, 'First Data Corp. (New)')
INSERT INTO Companies VALUES (497, 'First Division Ventures Inc.')
INSERT INTO Companies VALUES (498, 'First IC Corp.')
INSERT INTO Companies VALUES (499, 'First Interstate BancSystem, Inc.')
INSERT INTO Companies VALUES (500, 'First Mid Bancshares, Inc.')
INSERT INTO Companies VALUES (501, 'First Mid-Illinois Bancshares, Inc.')
INSERT INTO Companies VALUES (502, 'First Northern Community Bancorp')
INSERT INTO Companies VALUES (503, 'First Resource Bank')
INSERT INTO Companies VALUES (504, 'First Sound Bank (WA)')
INSERT INTO Companies VALUES (505, 'First South Bancorp, Inc. (S.C.)')
INSERT INTO Companies VALUES (506, 'First Trust Heitman Global Prime Real Estate ETF')
INSERT INTO Companies VALUES (507, 'First Trust Indxx NextG ETF')
INSERT INTO Companies VALUES (508, 'First Trust International Equity Opportunities ETF')
INSERT INTO Companies VALUES (509, 'First Trust International IPO ETF')
INSERT INTO Companies VALUES (510, 'First Trust NASDAQ Smartphone Index Fund')
INSERT INTO Companies VALUES (511, 'FirstService Corp. (New)')
INSERT INTO Companies VALUES (512, 'FitLife Brands, Inc.')
INSERT INTO Companies VALUES (513, 'Flexible Solutions International, Inc.')
INSERT INTO Companies VALUES (514, 'Flexible Solutions International, Inc. (Alberta, Canada)')
INSERT INTO Companies VALUES (515, 'flooidCX Corp.')
INSERT INTO Companies VALUES (516, 'Fluent, Inc.')
INSERT INTO Companies VALUES (517, 'Flybe Group plc')
INSERT INTO Companies VALUES (518, 'FMB Equibanc, Inc.')
INSERT INTO Companies VALUES (519, 'FMC Corp.')
INSERT INTO Companies VALUES (520, 'Fomento de Construcciones y Contratas SA')
INSERT INTO Companies VALUES (521, 'Footasylum plc')
INSERT INTO Companies VALUES (522, 'Forbes Energy Services Ltd. (TX)')
INSERT INTO Companies VALUES (523, 'Fortress REIT Ltd.')
INSERT INTO Companies VALUES (524, 'Fox Corp.')
INSERT INTO Companies VALUES (525, 'FPB Financial Corp.')
INSERT INTO Companies VALUES (526, 'Franchise Holdings International, Inc.')
INSERT INTO Companies VALUES (527, 'Fresenius Medical Care AG & Co. KGaA')
INSERT INTO Companies VALUES (528, 'FuelCell Energy, Inc.')
INSERT INTO Companies VALUES (529, 'Fuquan Financial Co.')
INSERT INTO Companies VALUES (530, 'Fuse Enterprises Inc.')
INSERT INTO Companies VALUES (531, 'Fuse Group Holding Inc.')
INSERT INTO Companies VALUES (532, 'Future Healthcare of America')
INSERT INTO Companies VALUES (533, 'Future International Group Corp.')
INSERT INTO Companies VALUES (534, 'G2 Goldfields Inc.')
INSERT INTO Companies VALUES (535, 'Gabelli Food of All Nations NextShares')
INSERT INTO Companies VALUES (536, 'Gabelli RBI NextShares')
INSERT INTO Companies VALUES (537, 'Galectin Therapeutics Inc.')
INSERT INTO Companies VALUES (538, 'Gaming Partners International Corp.')
INSERT INTO Companies VALUES (539, 'Gap, Inc. (The)')
INSERT INTO Companies VALUES (540, 'Gaucho Group Holdings, Inc.')
INSERT INTO Companies VALUES (541, 'Geant Corp.')
INSERT INTO Companies VALUES (542, 'Gemalto NV')
INSERT INTO Companies VALUES (543, 'General Electric Co.')
INSERT INTO Companies VALUES (544, 'Generex Biotechnology Corp.')
INSERT INTO Companies VALUES (545, 'Genocea Biosciences, Inc.')
INSERT INTO Companies VALUES (546, 'Genworth Financial, Inc. (New)')
INSERT INTO Companies VALUES (547, 'GeoVax Labs, Inc.')
INSERT INTO Companies VALUES (548, 'Getchell Gold Corp. (Canada)')
INSERT INTO Companies VALUES (549, 'GGP Inc.')
INSERT INTO Companies VALUES (550, 'Giant Motorsports, Inc.')
INSERT INTO Companies VALUES (551, 'Glacier Lake Resources Inc.')
INSERT INTO Companies VALUES (552, 'GlaxoSmithKline plc')
INSERT INTO Companies VALUES (553, 'Global Battery Metals Ltd.')
INSERT INTO Companies VALUES (554, 'Global Blockchain Technologies Corp.')
INSERT INTO Companies VALUES (555, 'Global Brass and Copper Holdings, Inc.')
INSERT INTO Companies VALUES (556, 'Global Fiber Technologies, Inc.')
INSERT INTO Companies VALUES (557, 'Global Gaming Technologies Corp.')
INSERT INTO Companies VALUES (558, 'Global Healthcare Income and Growth ETF')
INSERT INTO Companies VALUES (559, 'Global MobileTech, Inc.')
INSERT INTO Companies VALUES (560, 'Global Real Estate Dividend Growers Corp.')
INSERT INTO Companies VALUES (561, 'Global Ship Lease, Inc.')
INSERT INTO Companies VALUES (562, 'Global Wholehealth Partners Corp.')
INSERT INTO Companies VALUES (563, 'Glowpoint, Inc.')
INSERT INTO Companies VALUES (564, 'Gluskin Sheff & Associates Inc.')
INSERT INTO Companies VALUES (565, 'God''s Lake Resources Inc.')
INSERT INTO Companies VALUES (566, 'Goldcorp Inc.')
INSERT INTO Companies VALUES (567, 'Golden Share Resources Corp.')
INSERT INTO Companies VALUES (568, 'Golden Valley Bank')
INSERT INTO Companies VALUES (569, 'GoldSpot Discoveries Corp.')
INSERT INTO Companies VALUES (570, 'Government Properties Income Trust')
INSERT INTO Companies VALUES (571, 'Granada Gold Mine Inc.')
INSERT INTO Companies VALUES (572, 'Grand Peak Capital Corp.')
INSERT INTO Companies VALUES (573, 'GraniteShares Gold Trust')
INSERT INTO Companies VALUES (574, 'GraniteShares Platinum Trust')
INSERT INTO Companies VALUES (575, 'Graphene & Solar Technologies Ltd.')
INSERT INTO Companies VALUES (576, 'Graphite One Inc.')
INSERT INTO Companies VALUES (577, 'Graphite One Resources Inc.')
INSERT INTO Companies VALUES (578, 'Grayscale Bitcoin Trust')
INSERT INTO Companies VALUES (579, 'Grayscale Ethereum Classic Trust')
INSERT INTO Companies VALUES (580, 'Great Panther Mining Ltd.')
INSERT INTO Companies VALUES (581, 'Great Panther Silver Ltd.')
INSERT INTO Companies VALUES (582, 'Greatbanks Resources Ltd.')
INSERT INTO Companies VALUES (583, 'Greater Hudson Bank')
INSERT INTO Companies VALUES (584, 'Great-West Lifeco Inc.')
INSERT INTO Companies VALUES (585, 'Green Axis Capital Corp.')
INSERT INTO Companies VALUES (586, 'Green Bancorp, Inc.')
INSERT INTO Companies VALUES (587, 'Green Growth Brands Inc.')
INSERT INTO Companies VALUES (588, 'Green Organic Dutchman Holdings Ltd. (The)')
INSERT INTO Companies VALUES (589, 'Green Stream Holdings, Inc.')
INSERT INTO Companies VALUES (590, 'Green Zebra International Corp.')
INSERT INTO Companies VALUES (591, 'GreenBox POS')
INSERT INTO Companies VALUES (592, 'GreenBox Pos LLC')
INSERT INTO Companies VALUES (593, 'Greencore Group plc')
INSERT INTO Companies VALUES (594, 'Grenville Gold Corp.')
INSERT INTO Companies VALUES (595, 'Gripevine Inc.')
INSERT INTO Companies VALUES (596, 'Grow Capital, Inc.')
INSERT INTO Companies VALUES (597, 'Grow Condos, Inc.')
INSERT INTO Companies VALUES (598, 'GTY Technology Holdings Inc.')
INSERT INTO Companies VALUES (599, 'GTY Technology Holdings Inc. (MA)')
INSERT INTO Companies VALUES (600, 'Guaranty Bancorp')
INSERT INTO Companies VALUES (601, 'Guided Therapeutics Inc.')
INSERT INTO Companies VALUES (602, 'Gulf & Orient Steamship Company, Ltd.')
INSERT INTO Companies VALUES (603, 'Guozi Zhongyu Capital Holdings Co.')
INSERT INTO Companies VALUES (604, 'Hamilton Bancorp, Inc.')
INSERT INTO Companies VALUES (605, 'Hanwha Q CELLS Co., Ltd.')
INSERT INTO Companies VALUES (606, 'Happy Town Holdings, Inc.')
INSERT INTO Companies VALUES (607, 'Harborside Inc.')
INSERT INTO Companies VALUES (608, 'Hardide plc')
INSERT INTO Companies VALUES (609, 'Harrow Health, Inc.')
INSERT INTO Companies VALUES (610, 'Hartford Financial Services Group, Inc. (The)')
INSERT INTO Companies VALUES (611, 'Harvard Illinois Bancorp Inc.')
INSERT INTO Companies VALUES (612, 'Harvest Health & Recreation Inc.')
INSERT INTO Companies VALUES (613, 'Haymaker Acquisition Corp.')
INSERT INTO Companies VALUES (614, 'Health Management Associates, Inc. (New)')
INSERT INTO Companies VALUES (615, 'Healthscope Ltd. (New)')
INSERT INTO Companies VALUES (616, 'Heartland Financial USA, Inc.')
INSERT INTO Companies VALUES (617, 'Helijet International Inc.')
INSERT INTO Companies VALUES (618, 'Helvetia Holding AG')
INSERT INTO Companies VALUES (619, 'Hemfosa Fastigheter AB')
INSERT INTO Companies VALUES (620, 'Hemispherx Biopharma Inc.')
INSERT INTO Companies VALUES (621, 'Henkel AG & Co. KGaA')
INSERT INTO Companies VALUES (622, 'Henry Schein, Inc.')
INSERT INTO Companies VALUES (623, 'Hermitage Offshore Services Ltd.')
INSERT INTO Companies VALUES (624, 'Hess Corp.')
INSERT INTO Companies VALUES (625, 'Hestia Insight Inc.')
INSERT INTO Companies VALUES (626, 'HEXO Corp.')
INSERT INTO Companies VALUES (627, 'HFF, Inc.')
INSERT INTO Companies VALUES (628, 'Hickok Inc.')
INSERT INTO Companies VALUES (629, 'HICL Infrastructure Company Ltd.')
INSERT INTO Companies VALUES (630, 'HICL Infrastructure plc')
INSERT INTO Companies VALUES (631, 'Hi-Crush Inc.')
INSERT INTO Companies VALUES (632, 'Hi-Crush Partners LP')
INSERT INTO Companies VALUES (633, 'High Income Securities Fund (New)')
INSERT INTO Companies VALUES (634, 'High Sierra Technologies, Inc.')
INSERT INTO Companies VALUES (635, 'Highland Floating Rate Opportunities Fund')
INSERT INTO Companies VALUES (636, 'Highland Income Fund')
INSERT INTO Companies VALUES (637, 'Highlands Bancorp, Inc.')
INSERT INTO Companies VALUES (638, 'Highwood Oil Co. Ltd.')
INSERT INTO Companies VALUES (639, 'Hinterland Metals Inc.')
INSERT INTO Companies VALUES (640, 'Holloway Lodging Corp.')
INSERT INTO Companies VALUES (641, 'HomeFed Corp. (New)')
INSERT INTO Companies VALUES (642, 'HomeTown Bankshares Corp.')
INSERT INTO Companies VALUES (643, 'Hong Kong Exchanges and Clearing Ltd.')
INSERT INTO Companies VALUES (644, 'HopFed Bancorp, Inc.')
INSERT INTO Companies VALUES (645, 'Horizon Pharma plc')
INSERT INTO Companies VALUES (646, 'Horizon Therapeutics plc')
INSERT INTO Companies VALUES (647, 'Hortonworks, Inc.')
INSERT INTO Companies VALUES (648, 'Hovnanian Enterprises, Inc.')
INSERT INTO Companies VALUES (649, 'HSBC Holdings plc')
INSERT INTO Companies VALUES (650, 'Hub Deals Corp.')
INSERT INTO Companies VALUES (651, 'Hubb Ventures, Inc.')
INSERT INTO Companies VALUES (652, 'Hudson Global, Inc.')
INSERT INTO Companies VALUES (653, 'Hunt Companies VALUES Finance Trust, Inc.')
INSERT INTO Companies VALUES (654, 'Hunter Maritime Acquisition Corp.')
INSERT INTO Companies VALUES (655, 'Hutchison China MediTech Ltd.')
INSERT INTO Companies VALUES (656, 'I.D. Systems, Inc.')
INSERT INTO Companies VALUES (657, 'iA Financial Corp. Inc.')
INSERT INTO Companies VALUES (658, 'iAnthus Capital Holdings, Inc.')
INSERT INTO Companies VALUES (659, 'Iberdrola SA')
INSERT INTO Companies VALUES (660, 'Icahn Enterprises, L.P.')
INSERT INTO Companies VALUES (661, 'ICON ECI Fund Fifteen, L.P.')
INSERT INTO Companies VALUES (662, 'ICON Equipment and Corporate Infrastructure Fund Fourteen, L.P.')
INSERT INTO Companies VALUES (663, 'Icon Exploration Inc.')
INSERT INTO Companies VALUES (664, 'Iconic Brands, Inc.')
INSERT INTO Companies VALUES (665, 'Iconix Brand Group, Inc.')
INSERT INTO Companies VALUES (666, 'Idaho Independent Bank')
INSERT INTO Companies VALUES (667, 'Idemitsu Kosan Co. Ltd.')
INSERT INTO Companies VALUES (668, 'IDM Mining Ltd.')
INSERT INTO Companies VALUES (669, 'IFG Group plc')
INSERT INTO Companies VALUES (670, 'IGC Resources Inc.')
INSERT INTO Companies VALUES (671, 'Ignite International Brands, Ltd.')
INSERT INTO Companies VALUES (672, 'iKang Healthcare Group, Inc.')
INSERT INTO Companies VALUES (673, 'Imaginatik plc')
INSERT INTO Companies VALUES (674, 'Imagination Park Entertainment Inc.')
INSERT INTO Companies VALUES (675, 'Imagination Park Technologies Inc.')
INSERT INTO Companies VALUES (676, 'Immune Design Corp.')
INSERT INTO Companies VALUES (677, 'Immunic, Inc.')
INSERT INTO Companies VALUES (678, 'Impellam Group plc')
INSERT INTO Companies VALUES (679, 'Imperva, Inc.')
INSERT INTO Companies VALUES (680, 'Imprimis Pharmaceuticals, Inc.')
INSERT INTO Companies VALUES (681, 'Incumaker, Inc.')
INSERT INTO Companies VALUES (682, 'Independent Bank Corporation (Mass.)')
INSERT INTO Companies VALUES (683, 'Independent Bank Group, Inc.')
INSERT INTO Companies VALUES (684, 'Indus Holdings Inc.')
INSERT INTO Companies VALUES (685, 'Industrial Alliance Insurance and Financial Services Inc.')
INSERT INTO Companies VALUES (686, 'InfraREIT, Inc.')
INSERT INTO Companies VALUES (687, 'Ingersoll-Rand plc')
INSERT INTO Companies VALUES (688, 'Inmarsat plc')
INSERT INTO Companies VALUES (689, 'Innovus Pharmaceuticals, Inc.')
INSERT INTO Companies VALUES (690, 'InoLife Technologies, Inc.')
INSERT INTO Companies VALUES (691, 'Inpixon')
INSERT INTO Companies VALUES (692, 'InspireMD, Inc.')
INSERT INTO Companies VALUES (693, 'Integrated Asset Management Corp.')
INSERT INTO Companies VALUES (694, 'Integrated Device Technology, Inc.')
INSERT INTO Companies VALUES (695, 'Integrity Gaming Corp.')
INSERT INTO Companies VALUES (696, 'Interbit Ltd.')
INSERT INTO Companies VALUES (697, 'InterContinental Hotels Group PLC (New)')
INSERT INTO Companies VALUES (698, 'Intermolecular, Inc.')
INSERT INTO Companies VALUES (699, 'International Money Express, Inc.')
INSERT INTO Companies VALUES (700, 'International Speedway Corporation')
INSERT INTO Companies VALUES (701, 'International Wire Group Holdings, Inc.')
INSERT INTO Companies VALUES (702, 'Intersections Inc.')
INSERT INTO Companies VALUES (703, 'Intrinsic4D Inc.')
INSERT INTO Companies VALUES (704, 'Inuvo, Inc.')
INSERT INTO Companies VALUES (705, 'InventaBiotech, Inc.')
INSERT INTO Companies VALUES (706, 'Invesco Canadian Energy Income ETF')
INSERT INTO Companies VALUES (707, 'Invesco China All-Cap ETF')
INSERT INTO Companies VALUES (708, 'Invesco Chinese Yuan Dim Sum Bond ETF')
INSERT INTO Companies VALUES (709, 'Invesco DWA Momentum & Low Volatility Rotation ETF')
INSERT INTO Companies VALUES (710, 'Invesco Emerging Markets Infrastructure ETF')
INSERT INTO Companies VALUES (711, 'Invesco FTSE RAFI Asia Pacific ex-Japan ETF')
INSERT INTO Companies VALUES (712, 'Invesco Global Agriculture ETF')
INSERT INTO Companies VALUES (713, 'Invesco Global Gold and Precious Metals ETF')
INSERT INTO Companies VALUES (714, 'Invesco Multi-Factor Large Cap ETF')
INSERT INTO Companies VALUES (715, 'Invesco Multi-Strategy Alternative ETF')
INSERT INTO Companies VALUES (716, 'Invesco RAFI Strategic Developed ex-US ETF')
INSERT INTO Companies VALUES (717, 'Invesco RAFI Strategic Developed ex-US Small Company')
INSERT INTO Companies VALUES (718, 'Invesco RAFI Strategic Emerging Markets ETF')
INSERT INTO Companies VALUES (719, 'Invesco RAFI Strategic US ETF')
INSERT INTO Companies VALUES (720, 'Invesco RAFI Strategic US Small Company ETF')
INSERT INTO Companies VALUES (721, 'Invesco Russell 2000 Equal Weight ETF')
INSERT INTO Companies VALUES (722, 'Invesco S&P 100 Equal Weight ETF')
INSERT INTO Companies VALUES (723, 'Invesco S&P 500 Value With Momentum ETF')
INSERT INTO Companies VALUES (724, 'Invesco S&P SmallCap Utilities & Communication Services ETF')
INSERT INTO Companies VALUES (725, 'Invesco S&P SmallCap Utilities ETF')
INSERT INTO Companies VALUES (726, 'Invesco Strategic Developed ex-US ETF')
INSERT INTO Companies VALUES (727, 'Invesco Strategic Developed ex-US Small Company ETF')
INSERT INTO Companies VALUES (728, 'Invesco Strategic Emerging Markets ETF')
INSERT INTO Companies VALUES (729, 'Invesco Strategic US ETF')
INSERT INTO Companies VALUES (730, 'Invesco Strategic US Small Company ETF')
INSERT INTO Companies VALUES (731, 'Invesco U.S. Large Cap Optimized Volatility ETF')
INSERT INTO Companies VALUES (732, 'Invesco WilderHill Progressive Energy ETF')
INSERT INTO Companies VALUES (733, 'Invesco Wilshire Micro-Cap ETF')
INSERT INTO Companies VALUES (734, 'Invesco Wilshire US REIT ETF')
INSERT INTO Companies VALUES (735, 'Invesco Zacks International Multi-Asset Income ETF')
INSERT INTO Companies VALUES (736, 'Invesco Zacks Micro Cap ETF')
INSERT INTO Companies VALUES (737, 'Investment Technology Group, Inc. (New)')
INSERT INTO Companies VALUES (738, 'Invictus MD Strategies Corp.')
INSERT INTO Companies VALUES (739, 'Invion Ltd.')
INSERT INTO Companies VALUES (740, 'I-ON Communications Corp.')
INSERT INTO Companies VALUES (741, 'I-ON Digital Corp.')
INSERT INTO Companies VALUES (742, 'Ionic Brands Corp.')
INSERT INTO Companies VALUES (743, 'iPass Inc.')
INSERT INTO Companies VALUES (744, 'Ipsen SA')
INSERT INTO Companies VALUES (745, 'Iridium Communications Inc.')
INSERT INTO Companies VALUES (746, 'Ironwood Pharmaceuticals, Inc.')
INSERT INTO Companies VALUES (747, 'iShares Preferred and Income Securities ETF')
INSERT INTO Companies VALUES (748, 'iShares U.S. Preferred Stock ETF')
INSERT INTO Companies VALUES (749, 'Isramco, Inc.')
INSERT INTO Companies VALUES (750, 'ITEX Corp.')
INSERT INTO Companies VALUES (751, 'IVERIC bio, Inc.')
INSERT INTO Companies VALUES (752, 'Jardine Lloyd Thompson Group plc')
INSERT INTO Companies VALUES (753, 'Jardine Matheson Holdings Ltd.')
INSERT INTO Companies VALUES (754, 'Jardine Strategic Holdings Ltd.')
INSERT INTO Companies VALUES (755, 'Jason Industries, Inc.')
INSERT INTO Companies VALUES (756, 'Jayden Resources Inc. (Cayman Islands)')
INSERT INTO Companies VALUES (757, 'JMD Properties Inc.')
INSERT INTO Companies VALUES (758, 'Johnson Controls International plc')
INSERT INTO Companies VALUES (759, 'Jones Energy, Inc.')
INSERT INTO Companies VALUES (760, 'JPMorgan Chase & Co.')
INSERT INTO Companies VALUES (761, 'JPMorgan Diversified Return Europe Currency Hedged ETF')
INSERT INTO Companies VALUES (762, 'JPMorgan Diversified Return International Currency Hedged ETF')
INSERT INTO Companies VALUES (763, 'JRSIS Health Care Corp.')
INSERT INTO Companies VALUES (764, 'Kaixin Auto Group')
INSERT INTO Companies VALUES (765, 'Kannalife, Inc.')
INSERT INTO Companies VALUES (766, 'KAR Auction Services, Inc.')
INSERT INTO Companies VALUES (767, 'KBL Merger Corp. IV')
INSERT INTO Companies VALUES (768, 'KCAP Financial, Inc.')
INSERT INTO Companies VALUES (769, 'Kendrion NV')
INSERT INTO Companies VALUES (770, 'Keurig Dr Pepper Inc.')
INSERT INTO Companies VALUES (771, 'Keweenaw Financial Corp.')
INSERT INTO Companies VALUES (772, 'Keynes Technology Co. Ltd.')
INSERT INTO Companies VALUES (773, 'KeyW Holding Corp.')
INSERT INTO Companies VALUES (774, 'Khan Resources Inc.')
INSERT INTO Companies VALUES (775, 'Kinder Morgan Canada Ltd.')
INSERT INTO Companies VALUES (776, 'Kinderhook Bank Corp.')
INSERT INTO Companies VALUES (777, 'Kingsway Financial Services Inc.')
INSERT INTO Companies VALUES (778, 'Kingsway Financial Services Inc. (DE)')
INSERT INTO Companies VALUES (779, 'Kitov Pharma Ltd.')
INSERT INTO Companies VALUES (780, 'KLA-Tencor Corp.')
INSERT INTO Companies VALUES (781, 'KMG Chemicals, Inc.')
INSERT INTO Companies VALUES (782, 'Kontoor Brands, Inc.')
INSERT INTO Companies VALUES (783, 'KOPR Point Ventures Inc.')
INSERT INTO Companies VALUES (784, 'Korn Ferry')
INSERT INTO Companies VALUES (785, 'Korn/Ferry International')
INSERT INTO Companies VALUES (786, 'Kosmos Energy Ltd. (Bermuda)')
INSERT INTO Companies VALUES (787, 'L3 Technologies, Inc.')
INSERT INTO Companies VALUES (788, 'La Cortez Energy, Inc.')
INSERT INTO Companies VALUES (789, 'Laboratorio Reig Jofre SA')
INSERT INTO Companies VALUES (790, 'Ladbrokes Coral Group plc')
INSERT INTO Companies VALUES (791, 'Ladder Capital Corp.')
INSERT INTO Companies VALUES (792, 'Lakeland Bancorp, Inc.')
INSERT INTO Companies VALUES (793, 'LaSalle Hotel Properties')
INSERT INTO Companies VALUES (794, 'Lazard World Trust Fund')
INSERT INTO Companies VALUES (795, 'LeadFX Inc.')
INSERT INTO Companies VALUES (796, 'Leaf of Faith Beverage, Inc.')
INSERT INTO Companies VALUES (797, 'Legg Mason Developed ex-US Diversified Core ETF')
INSERT INTO Companies VALUES (798, 'Legg Mason Emerging Markets Diversified Core ETF')
INSERT INTO Companies VALUES (799, 'Legg Mason US Diversified Core ETF')
INSERT INTO Companies VALUES (800, 'Legion Metals Corp.')
INSERT INTO Companies VALUES (801, 'Leo Holdings Corp. (Cayman Islands)')
INSERT INTO Companies VALUES (802, 'Level Brands, Inc.')
INSERT INTO Companies VALUES (803, 'Levon Resources Ltd. (New)')
INSERT INTO Companies VALUES (804, 'Lewis & Clark Bank')
INSERT INTO Companies VALUES (805, 'LGBTQ Loyalty Holdings, Inc.')
INSERT INTO Companies VALUES (806, 'Liberty Bancorp, Inc. (MO)')
INSERT INTO Companies VALUES (807, 'Liberty Expedia Holdings, Inc.')
INSERT INTO Companies VALUES (808, 'LifeApps Brands Inc.')
INSERT INTO Companies VALUES (809, 'Lighthouse Bank (CA) ')
INSERT INTO Companies VALUES (810, 'Lighthouse Group plc')
INSERT INTO Companies VALUES (811, 'Lilly (Eli) & Co.')
INSERT INTO Companies VALUES (812, 'Linde AG')
INSERT INTO Companies VALUES (813, 'Lineage Grow Co. Ltd.')
INSERT INTO Companies VALUES (814, 'Liqtech International, Inc.')
INSERT INTO Companies VALUES (815, 'Livent Corp.')
INSERT INTO Companies VALUES (816, 'Local Shopping REIT plc')
INSERT INTO Companies VALUES (817, 'Lojas Renner S.A.')
INSERT INTO Companies VALUES (818, 'LondonMetric Property plc')
INSERT INTO Companies VALUES (819, 'Lone Star Gold, Inc.')
INSERT INTO Companies VALUES (820, 'Lonmin plc')
INSERT INTO Companies VALUES (821, 'Lorraine Copper Corp.')
INSERT INTO Companies VALUES (822, 'Loxo Oncology, Inc.')
INSERT INTO Companies VALUES (823, 'LSC Communications, Inc.')
INSERT INTO Companies VALUES (824, 'LSC Lithium Corp.')
INSERT INTO Companies VALUES (825, 'LTS Nutraceuticals, Inc.')
INSERT INTO Companies VALUES (826, 'Luxoft Holding, Inc.')
INSERT INTO Companies VALUES (827, 'Luxottica Group, S. P. A.')
INSERT INTO Companies VALUES (828, 'Luxshmi Investments, Inc.')
INSERT INTO Companies VALUES (829, 'LVMH-Moet Hennessy Louis Vuitton')
INSERT INTO Companies VALUES (830, 'M2 Cobalt Corp.')
INSERT INTO Companies VALUES (831, 'Magellan Gold Corp.')
INSERT INTO Companies VALUES (832, 'MagneGas Applied Technology Solutions, Inc.')
INSERT INTO Companies VALUES (833, 'Majesco')
INSERT INTO Companies VALUES (834, 'Majestic Oil & Gas, Inc.')
INSERT INTO Companies VALUES (835, 'Man Group plc (Jersey)')
INSERT INTO Companies VALUES (836, 'Man Group plc (New)')
INSERT INTO Companies VALUES (837, 'Manitex Capital Inc.')
INSERT INTO Companies VALUES (838, 'Marathon Patent Group, Inc.')
INSERT INTO Companies VALUES (839, 'Maricann Group Inc.')
INSERT INTO Companies VALUES (840, 'Marine Harvest ASA')
INSERT INTO Companies VALUES (841, 'Marks & Spencer Group plc')
INSERT INTO Companies VALUES (842, 'Marlin Gold Mining Ltd.')
INSERT INTO Companies VALUES (843, 'Marquie Group, Inc. (The)')
INSERT INTO Companies VALUES (844, 'Marsh & McLennan Companies, Inc.')
INSERT INTO Companies VALUES (845, 'Maxar Technologies Inc.')
INSERT INTO Companies VALUES (846, 'Maxar Technologies Ltd.')
INSERT INTO Companies VALUES (847, 'Maxwell Technologies Inc.')
INSERT INTO Companies VALUES (848, 'MB Financial, Inc. (New)')
INSERT INTO Companies VALUES (849, 'MBT Financial Corp.')
INSERT INTO Companies VALUES (850, 'McBride plc')
INSERT INTO Companies VALUES (851, 'mCig, Inc.')
INSERT INTO Companies VALUES (852, 'MDM Permian, Inc.')
INSERT INTO Companies VALUES (853, 'MDU Resources Group Inc.')
INSERT INTO Companies VALUES (854, 'MDU Resources Group Inc. (New)')
INSERT INTO Companies VALUES (855, 'MedCareers Group, Inc.')
INSERT INTO Companies VALUES (856, 'MedEquities Realty Trust, Inc.')
INSERT INTO Companies VALUES (857, 'Medical Transcription Billing, Corp.')
INSERT INTO Companies VALUES (858, 'MedicX Fund Ltd.')
INSERT INTO Companies VALUES (859, 'Medley Capital Corp.')
INSERT INTO Companies VALUES (860, 'Medley Management Inc.')
INSERT INTO Companies VALUES (861, 'Medtainer, Inc.')
INSERT INTO Companies VALUES (862, 'MEG Energy Corp.')
INSERT INTO Companies VALUES (863, 'Melco International Development Ltd.')
INSERT INTO Companies VALUES (864, 'Melinta Therapeutics, Inc.')
INSERT INTO Companies VALUES (865, 'Mellanox Technologies Ltd.')
INSERT INTO Companies VALUES (866, 'Melt, Inc.')
INSERT INTO Companies VALUES (867, 'Merck & Co., Inc. (New)')
INSERT INTO Companies VALUES (868, 'Mereo BioPharma Group plc')
INSERT INTO Companies VALUES (869, 'Metro, Inc. (2019)')
INSERT INTO Companies VALUES (870, 'Metropolitan Energy Corp.')
INSERT INTO Companies VALUES (871, 'Mexico Equity & Income Fund, Inc.')
INSERT INTO Companies VALUES (872, 'Mezzotin Minerals Inc.')
INSERT INTO Companies VALUES (873, 'Michael Kors Holdings Ltd.')
INSERT INTO Companies VALUES (874, 'Micro Focus International plc')
INSERT INTO Companies VALUES (875, 'Microgen plc')
INSERT INTO Companies VALUES (876, 'MICT, Inc.')
INSERT INTO Companies VALUES (877, 'Midatech Pharma PLC')
INSERT INTO Companies VALUES (878, 'Middlefield Healthcare & Life Sciences Dividend Fund')
INSERT INTO Companies VALUES (879, 'Middlefield Healthcare & Life Sciences ETF')
INSERT INTO Companies VALUES (880, 'Middlefield REIT INDEXPLUS ETF')
INSERT INTO Companies VALUES (881, 'MidSouth Bancorp, Inc.')
INSERT INTO Companies VALUES (882, 'Midstates Petroleum Company, Inc.')
INSERT INTO Companies VALUES (883, 'Minco Capital Corp.')
INSERT INTO Companies VALUES (884, 'Minco Gold Corp.')
INSERT INTO Companies VALUES (885, 'MINDBODY, Inc.')
INSERT INTO Companies VALUES (886, 'Miranda Gold Corp.')
INSERT INTO Companies VALUES (887, 'MITU Resources Inc.')
INSERT INTO Companies VALUES (888, 'MJ Venture Partners, Inc.')
INSERT INTO Companies VALUES (889, 'MKS Instruments, Inc.')
INSERT INTO Companies VALUES (890, 'ML Gold Corp.')
INSERT INTO Companies VALUES (891, 'MMA Capital Holdings, Inc.')
INSERT INTO Companies VALUES (892, 'MMA Capital Management, LLC')
INSERT INTO Companies VALUES (893, 'Mobio Technologies Inc.')
INSERT INTO Companies VALUES (894, 'Modern Media Acquisition Corp.')
INSERT INTO Companies VALUES (895, 'Modern Times Group MTG AB')
INSERT INTO Companies VALUES (896, 'Modular Space Holdings, Inc.')
INSERT INTO Companies VALUES (897, 'MOGO Finance Technology Inc.')
INSERT INTO Companies VALUES (898, 'Monarch Gold Corp.')
INSERT INTO Companies VALUES (899, 'Monarques Gold Corp.')
INSERT INTO Companies VALUES (900, 'Mondi Ltd.')
INSERT INTO Companies VALUES (901, 'Montage Resources Corp.')
INSERT INTO Companies VALUES (902, 'Montan Mining Corp.')
INSERT INTO Companies VALUES (903, 'Morgan Stanley')
INSERT INTO Companies VALUES (904, 'Morgan Stanley Asia-Pacific Fund, Inc. (New)')
INSERT INTO Companies VALUES (905, 'Morgan Stanley Emerging Markets Fund, Inc. (New)')
INSERT INTO Companies VALUES (906, 'Mowi ASA')
INSERT INTO Companies VALUES (907, 'Moxian, Inc.')
INSERT INTO Companies VALUES (908, 'mPhase Technologies, Inc.')
INSERT INTO Companies VALUES (909, 'MPM Holdings Inc.')
INSERT INTO Companies VALUES (910, 'MPX Bioceutical Corp.')
INSERT INTO Companies VALUES (911, 'MPX International Corp.')
INSERT INTO Companies VALUES (912, 'MSA Safety Inc.')
INSERT INTO Companies VALUES (913, 'MTBC, Inc.')
INSERT INTO Companies VALUES (914, 'MTGE Investment Corp.')
INSERT INTO Companies VALUES (915, 'MTY Food Group Inc.')
INSERT INTO Companies VALUES (916, 'Muliang Agritech, Inc.')
INSERT INTO Companies VALUES (917, 'Mullan Agritech, Inc.')
INSERT INTO Companies VALUES (918, 'MultiChoice Group Ltd.')
INSERT INTO Companies VALUES (919, 'Multi-Color Corp.')
INSERT INTO Companies VALUES (920, 'Muncy Bank Financial, Inc.')
INSERT INTO Companies VALUES (921, 'Murata Manufacturing Co. Ltd.')
INSERT INTO Companies VALUES (922, 'Music of Your Life, Inc.')
INSERT INTO Companies VALUES (923, 'Must Capital Inc.')
INSERT INTO Companies VALUES (924, 'MXC Capital Ltd.')
INSERT INTO Companies VALUES (925, 'MYnd Analytics, Inc.')
INSERT INTO Companies VALUES (926, 'NanoSensors, Inc.')
INSERT INTO Companies VALUES (927, 'Naspers Ltd.')
INSERT INTO Companies VALUES (928, 'National Commerce Corp.')
INSERT INTO Companies VALUES (929, 'National Grid plc')
INSERT INTO Companies VALUES (930, 'Natur International Corp.')
INSERT INTO Companies VALUES (931, 'Natura Cosmeticos S.A.')
INSERT INTO Companies VALUES (932, 'Nature''s Best Brands, Inc.')
INSERT INTO Companies VALUES (933, 'Natuzzi S.p.A.')
INSERT INTO Companies VALUES (934, 'Navidea Biopharmaceuticals, Inc.')
INSERT INTO Companies VALUES (935, 'Navigators Group, Inc.')
INSERT INTO Companies VALUES (936, 'Navios Maritime Holdings Inc.')
INSERT INTO Companies VALUES (937, 'Navios Maritime Partners L.P.')
INSERT INTO Companies VALUES (938, 'NCI Building Systems, Inc.')
INSERT INTO Companies VALUES (939, 'NCR Corp. (New)')
INSERT INTO Companies VALUES (940, 'Nemus Bioscience, Inc.')
INSERT INTO Companies VALUES (941, 'Neo Performance Materials Inc.')
INSERT INTO Companies VALUES (942, 'Neon Bloom, Inc. ')
INSERT INTO Companies VALUES (943, 'Neste Oyj')
INSERT INTO Companies VALUES (944, 'NETGEAR, Inc.')
INSERT INTO Companies VALUES (945, 'Netshoes (Cayman) Ltd.')
INSERT INTO Companies VALUES (946, 'Nevada Clean Magnesium Inc.')
INSERT INTO Companies VALUES (947, 'Nevada Gold & Casinos Inc.')
INSERT INTO Companies VALUES (948, 'Nevsun Resources Ltd.')
INSERT INTO Companies VALUES (949, 'New Age Brands Inc.')
INSERT INTO Companies VALUES (950, 'New Energy Metals Corp.')
INSERT INTO Companies VALUES (951, 'New Point Exploration Corp.')
INSERT INTO Companies VALUES (952, 'New Tech Lithium Corp.')
INSERT INTO Companies VALUES (953, 'New Tech Minerals Corp.')
INSERT INTO Companies VALUES (954, 'New York REIT, Inc.')
INSERT INTO Companies VALUES (955, 'New You, Inc.')
INSERT INTO Companies VALUES (956, 'Newfield Exploration Company')
INSERT INTO Companies VALUES (957, 'Newmont Goldcorp Corp.')
INSERT INTO Companies VALUES (958, 'Newmont Mining Corp.')
INSERT INTO Companies VALUES (959, 'NewRiver REIT plc')
INSERT INTO Companies VALUES (960, 'Newstrike Brands Ltd.')
INSERT INTO Companies VALUES (961, 'Nexeo Solutions, Inc.')
INSERT INTO Companies VALUES (962, 'NexPoint Strategic Opportunities Fund')
INSERT INTO Companies VALUES (963, 'Nextleaf Solutions Ltd.')
INSERT INTO Companies VALUES (964, 'nFusz, Inc.')
INSERT INTO Companies VALUES (965, 'Nightstar Therapeutics plc')
INSERT INTO Companies VALUES (966, 'Nordic Entertainment Group AB')
INSERT INTO Companies VALUES (967, 'Norra Metals Corp.')
INSERT INTO Companies VALUES (968, 'Northeast Bancorp (New)')
INSERT INTO Companies VALUES (969, 'Northeast Bank')
INSERT INTO Companies VALUES (970, 'Northern Superior Resources Inc.')
INSERT INTO Companies VALUES (971, 'NorthWest Indiana Bancorp')
INSERT INTO Companies VALUES (972, 'Novartis AG')
INSERT INTO Companies VALUES (973, 'Novavax, Inc.')
INSERT INTO Companies VALUES (974, 'Novume Solutions, Inc.')
INSERT INTO Companies VALUES (975, 'NRG Metals Inc.')
INSERT INTO Companies VALUES (976, 'NutraFuels, Inc.')
INSERT INTO Companies VALUES (977, 'NutraLife BioSciences, Inc.')
INSERT INTO Companies VALUES (978, 'Nutrisystem, Inc.')
INSERT INTO Companies VALUES (979, 'Nuveen Taxable Municipal Income Fund')
INSERT INTO Companies VALUES (980, 'Nvest Inc.')
INSERT INTO Companies VALUES (981, 'NX Uranium, Inc.')
INSERT INTO Companies VALUES (982, 'NxStage Medical, Inc.')
INSERT INTO Companies VALUES (983, 'Nyfosa AB')
INSERT INTO Companies VALUES (984, 'Ocean Power Technologies, Inc.')
INSERT INTO Companies VALUES (985, 'OceanFirst Financial Corp.')
INSERT INTO Companies VALUES (986, 'Och-Ziff Capital Management Group LLC')
INSERT INTO Companies VALUES (987, 'OCI N.V.')
INSERT INTO Companies VALUES (988, 'Office Properties Income Trust')
INSERT INTO Companies VALUES (989, 'Ohr Pharmaceutical, Inc. (New)')
INSERT INTO Companies VALUES (990, 'Oi S.A.')
INSERT INTO Companies VALUES (991, 'Oil Search Ltd.')
INSERT INTO Companies VALUES (992, 'OK2 Minerals Ltd.')
INSERT INTO Companies VALUES (993, 'Olympus Corp.')
INSERT INTO Companies VALUES (994, 'Omega Healthcare Investors, Inc.')
INSERT INTO Companies VALUES (995, 'OncoMed Pharmaceuticals, Inc.')
INSERT INTO Companies VALUES (996, 'OncoSec Medical Inc.')
INSERT INTO Companies VALUES (997, 'One Madison Corp.')
INSERT INTO Companies VALUES (998, 'One World Pharma, Inc.')
INSERT INTO Companies VALUES (999, 'OneSpaWorld Holdings Ltd.')
INSERT INTO Companies VALUES (1000, 'Ophir Energy plc')
INSERT INTO Companies VALUES (1001, 'Ophthotech Corp.')
INSERT INTO Companies VALUES (1002, 'Oppenheimer ETF Trust')
INSERT INTO Companies VALUES (1003, 'Optium Cyber Systems, Inc.')
INSERT INTO Companies VALUES (1004, 'Orbotech Ltd.')
INSERT INTO Companies VALUES (1005, 'Orchid Ventures Inc.')
INSERT INTO Companies VALUES (1006, 'Orofino Minerals Inc.')
INSERT INTO Companies VALUES (1007, 'Oroplata Resources, Inc.')
INSERT INTO Companies VALUES (1008, 'Orrstown Financial Services, Inc.')
INSERT INTO Companies VALUES (1009, 'Osiris Therapeutics, Inc.')
INSERT INTO Companies VALUES (1010, 'OurPet''s Company')
INSERT INTO Companies VALUES (1011, 'Outcrop Gold Corp.')
INSERT INTO Companies VALUES (1012, 'Outlook Therapeutics, Inc.')
INSERT INTO Companies VALUES (1013, 'Owens Realty Mortgage, Inc.')
INSERT INTO Companies VALUES (1014, 'Pacific Biosciences of California, Inc.')
INSERT INTO Companies VALUES (1015, 'Pacific Conquest Holdings, Inc.')
INSERT INTO Companies VALUES (1016, 'Pacific Office Properties Trust, Inc.')
INSERT INTO Companies VALUES (1017, 'Pacific Shore Holdings, Inc.')
INSERT INTO Companies VALUES (1018, 'Pacific Software, Inc.')
INSERT INTO Companies VALUES (1019, 'Pacira BioSciences, Inc.')
INSERT INTO Companies VALUES (1020, 'Pacira Pharmaceuticals, Inc.')
INSERT INTO Companies VALUES (1021, 'Pacman Media Inc.')
INSERT INTO Companies VALUES (1022, 'Pain Therapeutics, Inc.')
INSERT INTO Companies VALUES (1023, 'Paloma Resources Inc.')
INSERT INTO Companies VALUES (1024, 'Pan American Silver Corp.')
INSERT INTO Companies VALUES (1025, 'Pan Pacific International Holdings Corp.')
INSERT INTO Companies VALUES (1026, 'Pandora Media, Inc.')
INSERT INTO Companies VALUES (1027, 'Papa Murphy''s Holdings, Inc.')
INSERT INTO Companies VALUES (1028, 'Pareteum Corp.')
INSERT INTO Companies VALUES (1029, 'Park National Corp. (Newark, Ohio)')
INSERT INTO Companies VALUES (1030, 'Park Place Energy Inc.')
INSERT INTO Companies VALUES (1031, 'Parker Drilling Co.')
INSERT INTO Companies VALUES (1032, 'Paysign, Inc.')
INSERT INTO Companies VALUES (1033, 'PCF Group plc')
INSERT INTO Companies VALUES (1034, 'PDS Biotechnology Corp.')
INSERT INTO Companies VALUES (1035, 'Penn Virginia Corp.')
INSERT INTO Companies VALUES (1036, 'Pensare Acquisition Corp.')
INSERT INTO Companies VALUES (1037, 'Peoples Bank of Commerce (OR)')
INSERT INTO Companies VALUES (1038, 'People''s United Financial, Inc.')
INSERT INTO Companies VALUES (1039, 'Performance Shipping Inc.')
INSERT INTO Companies VALUES (1040, 'Perlite Canada Inc.')
INSERT INTO Companies VALUES (1041, 'Pershing Gold Corp.')
INSERT INTO Companies VALUES (1042, 'Petro Vista Energy Corp.')
INSERT INTO Companies VALUES (1043, 'PetroGas Co.')
INSERT INTO Companies VALUES (1044, 'PGIM Global High Yield Fund, Inc.')
INSERT INTO Companies VALUES (1045, 'PGIM Global Short Duration High Yield Fund, Inc.')
INSERT INTO Companies VALUES (1046, 'PGIM High Yield Bond Fund, Inc.')
INSERT INTO Companies VALUES (1047, 'PGIM Short Duration High Yield Fund, Inc.')
INSERT INTO Companies VALUES (1048, 'PharmaCielo Ltd.')
INSERT INTO Companies VALUES (1049, 'PHMC, Inc.')
INSERT INTO Companies VALUES (1050, 'Phoenix Gold Resources Corp.')
INSERT INTO Companies VALUES (1051, 'Phoenix International Ventures Inc.')
INSERT INTO Companies VALUES (1052, 'PhoneX Holdings, Inc.')
INSERT INTO Companies VALUES (1053, 'Pilgrim Bancshares, Inc.')
INSERT INTO Companies VALUES (1054, 'Pinnacle Renewable Energy Inc.')
INSERT INTO Companies VALUES (1055, 'Pinnacle Renewable Holdings Inc.')
INSERT INTO Companies VALUES (1056, 'Pioneer Railcorp')
INSERT INTO Companies VALUES (1057, 'Pipestone Energy Corp.')
INSERT INTO Companies VALUES (1058, 'Platform Specialty Products Corp. (DE)')
INSERT INTO Companies VALUES (1059, 'Platforms Wireless International Corp.')
INSERT INTO Companies VALUES (1060, 'Platinum Eagle Acquisition Corp.')
INSERT INTO Companies VALUES (1061, 'Platinum Eagle Acquisition Corp. (DE)')
INSERT INTO Companies VALUES (1062, 'PlayAGS, Inc.')
INSERT INTO Companies VALUES (1063, 'Pocket Shot Co.')
INSERT INTO Companies VALUES (1064, 'Pointer Telocation Ltd.')
INSERT INTO Companies VALUES (1065, 'Polemos plc')
INSERT INTO Companies VALUES (1066, 'Portman Ridge Finance Corp.')
INSERT INTO Companies VALUES (1067, 'Portofino Resources Inc.')
INSERT INTO Companies VALUES (1068, 'Post Holdings, Inc.')
INSERT INTO Companies VALUES (1069, 'PostNL NV')
INSERT INTO Companies VALUES (1070, 'PotlatchDeltic Corp.')
INSERT INTO Companies VALUES (1071, 'Power Corp. of Canada')
INSERT INTO Companies VALUES (1072, 'Power Financial Corp.')
INSERT INTO Companies VALUES (1073, 'Power Group Projects Corp.')
INSERT INTO Companies VALUES (1074, 'Prana Biotechnology Ltd.')
INSERT INTO Companies VALUES (1075, 'PreCheck Health Services, Inc.')
INSERT INTO Companies VALUES (1076, 'Precious Investments, Inc.')
INSERT INTO Companies VALUES (1077, 'Precipio, Inc.')
INSERT INTO Companies VALUES (1078, 'Predator Blockchain Capital Corp.')
INSERT INTO Companies VALUES (1079, 'Presidio Bank')
INSERT INTO Companies VALUES (1080, 'Primary Energy Metals Inc.')
INSERT INTO Companies VALUES (1081, 'Primary Health Properties plc')
INSERT INTO Companies VALUES (1082, 'PrimeEnergy Corp.')
INSERT INTO Companies VALUES (1083, 'PrimeEnergy Resources Corp.')
INSERT INTO Companies VALUES (1084, 'Priority Technology Holdings, Inc.')
INSERT INTO Companies VALUES (1085, 'Produce Investments plc')
INSERT INTO Companies VALUES (1086, 'ProMetic Life Sciences Inc.')
INSERT INTO Companies VALUES (1087, 'Promotora de Informaciones, S.A.')
INSERT INTO Companies VALUES (1088, 'Prosegur Compania de Seguridad, S.A.')
INSERT INTO Companies VALUES (1089, 'ProShares UltraPro Short Dow30')
INSERT INTO Companies VALUES (1090, 'ProShares UltraPro Short QQQ')
INSERT INTO Companies VALUES (1091, 'ProShares UltraShort Semiconductors')
INSERT INTO Companies VALUES (1092, 'ProShares UltraShort Technology')
INSERT INTO Companies VALUES (1093, 'ProSports Sponsors ETF')
INSERT INTO Companies VALUES (1094, 'Provident Financial plc')
INSERT INTO Companies VALUES (1095, 'PSB Holding Corp.')
INSERT INTO Companies VALUES (1096, 'PT Medco Energi Internasional TBK ')
INSERT INTO Companies VALUES (1097, 'Public Storage (MD)')
INSERT INTO Companies VALUES (1098, 'Pulmatrix, Inc.')
INSERT INTO Companies VALUES (1099, 'Pulse Evolution Group, Inc.')
INSERT INTO Companies VALUES (1100, 'Punto Group, Corp.')
INSERT INTO Companies VALUES (1101, 'Pure Harvest Cannabis Group, Inc.')
INSERT INTO Companies VALUES (1102, 'Quantenna Communications, Inc.')
INSERT INTO Companies VALUES (1103, 'Quantum Capital, Inc.')
INSERT INTO Companies VALUES (1104, 'Quantum International Income Corp.')
INSERT INTO Companies VALUES (1105, 'QX Metals Corp.')
INSERT INTO Companies VALUES (1106, 'Radiant Creations Group, Inc. (The)')
INSERT INTO Companies VALUES (1107, 'Randall Bearings Inc.')
INSERT INTO Companies VALUES (1108, 'Randgold Resources Ltd.')
INSERT INTO Companies VALUES (1109, 'Ranpak Holdings Corp.')
INSERT INTO Companies VALUES (1110, 'Rapier Gold Inc.')
INSERT INTO Companies VALUES (1111, 'Rarus Technologies Inc.')
INSERT INTO Companies VALUES (1112, 'Raven Property Group Ltd.')
INSERT INTO Companies VALUES (1113, 'RDI REIT P.L.C.')
INSERT INTO Companies VALUES (1114, 'REAC Group, Inc.')
INSERT INTO Companies VALUES (1115, 'Ready Capital Corp.')
INSERT INTO Companies VALUES (1116, 'RealSource Residential, Inc.')
INSERT INTO Companies VALUES (1117, 'Recall Studios, Inc. ')
INSERT INTO Companies VALUES (1118, 'Recruiter.com Group, Inc.')
INSERT INTO Companies VALUES (1119, 'Red Hat, Inc.')
INSERT INTO Companies VALUES (1120, 'Redefy Corp.')
INSERT INTO Companies VALUES (1121, 'Redrow plc')
INSERT INTO Companies VALUES (1122, 'Redzone Resources Ltd.')
INSERT INTO Companies VALUES (1123, 'Reebonz Holding Ltd.')
INSERT INTO Companies VALUES (1124, 'Regional Health Properties, Inc.')
INSERT INTO Companies VALUES (1125, 'Reinhart Intermediate Bond NextShares')
INSERT INTO Companies VALUES (1126, 'REIT INDEXPLUS Income Fund')
INSERT INTO Companies VALUES (1127, 'Rekor Systems, Inc.')
INSERT INTO Companies VALUES (1128, 'Reliance Bancshares, Inc. (New)')
INSERT INTO Companies VALUES (1129, 'Renesas Electronics Corp.')
INSERT INTO Companies VALUES (1130, 'Renmin Tianli Group, Inc.')
INSERT INTO Companies VALUES (1131, 'RENN Fund, Inc.')
INSERT INTO Companies VALUES (1132, 'Repsol, S.A. (New)')
INSERT INTO Companies VALUES (1133, 'Resilient REIT Ltd.')
INSERT INTO Companies VALUES (1134, 'Resolute Energy Corp.')
INSERT INTO Companies VALUES (1135, 'Results-Based Outsourcing Inc.')
INSERT INTO Companies VALUES (1136, 'Retail Value Inc.')
INSERT INTO Companies VALUES (1137, 'Revival, Inc.')
INSERT INTO Companies VALUES (1138, 'ReWalk Robotics Ltd.')
INSERT INTO Companies VALUES (1139, 'REX BKCM ETF')
INSERT INTO Companies VALUES (1140, 'Rexahn Pharmaceuticals, Inc.')
INSERT INTO Companies VALUES (1141, 'Rhythmone plc')
INSERT INTO Companies VALUES (1142, 'Ripper Oil & Gas Inc.')
INSERT INTO Companies VALUES (1143, 'Rite Aid Corp.')
INSERT INTO Companies VALUES (1144, 'River Wild Exploration Inc.')
INSERT INTO Companies VALUES (1145, 'RMD Entertainment Group')
INSERT INTO Companies VALUES (1146, 'Roadman Investments Corp.')
INSERT INTO Companies VALUES (1147, 'Roadrunner Transportation Systems, Inc.')
INSERT INTO Companies VALUES (1148, 'Rockbridge Resources Inc.')
INSERT INTO Companies VALUES (1149, 'Rockwell Collins, Inc.')
INSERT INTO Companies VALUES (1150, 'Rocky Mountain High Brands, Inc.')
INSERT INTO Companies VALUES (1151, 'Rogue Station Companies, Inc.')
INSERT INTO Companies VALUES (1152, 'Rolls-Royce Holdings plc')
INSERT INTO Companies VALUES (1153, 'Rotation Minerals Ltd.')
INSERT INTO Companies VALUES (1154, 'Rowan Companies VALUES plc')
INSERT INTO Companies VALUES (1155, 'Royce Micro-Cap Trust, Inc.')
INSERT INTO Companies VALUES (1156, 'Royce Value Trust, Inc.')
INSERT INTO Companies VALUES (1157, 'RPC Group plc')
INSERT INTO Companies VALUES (1158, 'RTI Surgical Holdings, Inc.')
INSERT INTO Companies VALUES (1159, 'RTI Surgical, Inc.')
INSERT INTO Companies VALUES (1160, 'Saban Capital Acquisition Corp.')
INSERT INTO Companies VALUES (1161, 'Sacyr S.A.')
INSERT INTO Companies VALUES (1162, 'Safehold Inc.')
INSERT INTO Companies VALUES (1163, 'Safeland plc')
INSERT INTO Companies VALUES (1164, 'Safety, Income & Growth Inc.')
INSERT INTO Companies VALUES (1165, 'Sagittarius Capital Corp.')
INSERT INTO Companies VALUES (1166, 'Saker Aviation, Inc.')
INSERT INTO Companies VALUES (1167, 'SalvaRx Group plc')
INSERT INTO Companies VALUES (1168, 'San Leon Energy plc')
INSERT INTO Companies VALUES (1169, 'Sanara MedTech Inc.')
INSERT INTO Companies VALUES (1170, 'Sanchez Energy Corp.')
INSERT INTO Companies VALUES (1171, 'Sandy Lake Gold Inc.')
INSERT INTO Companies VALUES (1172, 'SanSal Wellness Holdings, Inc.')
INSERT INTO Companies VALUES (1173, 'Saputo Inc.')
INSERT INTO Companies VALUES (1174, 'Savary Gold Corp.')
INSERT INTO Companies VALUES (1175, 'SBT Bancorp, Inc. (CT)')
INSERT INTO Companies VALUES (1176, 'SCANA Corp.')
INSERT INTO Companies VALUES (1177, 'Schibsted ASA')
INSERT INTO Companies VALUES (1178, 'Schulman (A.), Inc.')
INSERT INTO Companies VALUES (1179, 'Science Applications International Corp.')
INSERT INTO Companies VALUES (1180, 'Scorpio Tankers Inc.')
INSERT INTO Companies VALUES (1181, 'Scottie Resources Corp.')
INSERT INTO Companies VALUES (1182, 'SCWorx Corp.')
INSERT INTO Companies VALUES (1183, 'SDX Energy Inc.')
INSERT INTO Companies VALUES (1184, 'SDX Energy plc')
INSERT INTO Companies VALUES (1185, 'Seamless Technology, Inc.')
INSERT INTO Companies VALUES (1186, 'Seanergy Maritime Holdings Corp.')
INSERT INTO Companies VALUES (1187, 'Search Minerals Inc.')
INSERT INTO Companies VALUES (1188, 'Second Sight Medical Products, Inc.')
INSERT INTO Companies VALUES (1189, 'SecurCapital Holdings Corp.')
INSERT INTO Companies VALUES (1190, 'Seeker Tec International Inc.')
INSERT INTO Companies VALUES (1191, 'Seelos Therapeutics, Inc.')
INSERT INTO Companies VALUES (1192, 'SEGRO PLC')
INSERT INTO Companies VALUES (1193, 'Select Income REIT')
INSERT INTO Companies VALUES (1194, 'SEMAFO Inc.')
INSERT INTO Companies VALUES (1195, 'Sempra Energy, Inc.')
INSERT INTO Companies VALUES (1196, 'SendGrid, Inc.')
INSERT INTO Companies VALUES (1197, 'Sentinel Energy Services Inc.')
INSERT INTO Companies VALUES (1198, 'Sentinel Energy Services Inc. (DE)')
INSERT INTO Companies VALUES (1199, 'SerenityShares Impact ETF')
INSERT INTO Companies VALUES (1200, 'Seven Aces Ltd.')
INSERT INTO Companies VALUES (1201, 'Shale Oil International Inc.')
INSERT INTO Companies VALUES (1202, 'Sharing Services Global Corp.')
INSERT INTO Companies VALUES (1203, 'Sharing Services, Inc.')
INSERT INTO Companies VALUES (1204, 'Shawcor Ltd. (New)')
INSERT INTO Companies VALUES (1205, 'Shionogi & Co., Ltd.')
INSERT INTO Companies VALUES (1206, 'Shire plc (New)')
INSERT INTO Companies VALUES (1207, 'Showa Shell Sekiyu K.K.')
INSERT INTO Companies VALUES (1208, 'SI Financial Group, Inc. (MD)')
INSERT INTO Companies VALUES (1209, 'Sierra Growth Corp.')
INSERT INTO Companies VALUES (1210, 'Sierra Madre Developments Inc.')
INSERT INTO Companies VALUES (1211, 'Sierra Monitor Corp.')
INSERT INTO Companies VALUES (1212, 'Silver Phoenix Resources Inc.')
INSERT INTO Companies VALUES (1213, 'Simmons First National Corp.')
INSERT INTO Companies VALUES (1214, 'Simplicity Esports and Gaming Co.')
INSERT INTO Companies VALUES (1215, 'Sino Land Company Ltd. ')
INSERT INTO Companies VALUES (1216, 'Sinovac Biotech, Ltd.')
INSERT INTO Companies VALUES (1217, 'Sirius XM Holdings Inc.')
INSERT INTO Companies VALUES (1218, 'SITE Centers Corp.')
INSERT INTO Companies VALUES (1219, 'Skinvisible, Inc.')
INSERT INTO Companies VALUES (1220, 'Skychain Technologies Inc.')
INSERT INTO Companies VALUES (1221, 'Slate Retail REIT')
INSERT INTO Companies VALUES (1222, 'Smaaash Entertainment Inc.')
INSERT INTO Companies VALUES (1223, 'Smart & Final Stores, Inc.')
INSERT INTO Companies VALUES (1224, 'SMC Ventures Inc.')
INSERT INTO Companies VALUES (1225, 'Smith & Nephew PLC')
INSERT INTO Companies VALUES (1226, 'SMTC Corp.')
INSERT INTO Companies VALUES (1227, 'Softlab9 Software Solutions Inc.')
INSERT INTO Companies VALUES (1228, 'Sojourn Exploration Inc.')
INSERT INTO Companies VALUES (1229, 'Sokoman Iron Corp.')
INSERT INTO Companies VALUES (1230, 'Sokoman Minerals Corp.')
INSERT INTO Companies VALUES (1231, 'Solar Capital Ltd.')
INSERT INTO Companies VALUES (1232, 'Solar Quartz Technology Corp.')
INSERT INTO Companies VALUES (1233, 'Solar Senior Capital Ltd.')
INSERT INTO Companies VALUES (1234, 'Solium Capital Inc.')
INSERT INTO Companies VALUES (1235, 'Solo Growth Corp.')
INSERT INTO Companies VALUES (1236, 'Somerset Transition Corp.')
INSERT INTO Companies VALUES (1237, 'Southern Energy Corp.')
INSERT INTO Companies VALUES (1238, 'Spark Therapeutics, Inc.')
INSERT INTO Companies VALUES (1239, 'Sparton Corp.')
INSERT INTO Companies VALUES (1240, 'SPDR Bloomberg Barclays High Yield Bond ETF')
INSERT INTO Companies VALUES (1241, 'Spectacular Solar, Inc.')
INSERT INTO Companies VALUES (1242, 'Spectra Energy Partners, LP')
INSERT INTO Companies VALUES (1243, 'Spherix Incorporated')
INSERT INTO Companies VALUES (1244, 'Spirit Realty Capital, Inc. (New) ')
INSERT INTO Companies VALUES (1245, 'Sport Endurance Inc.')
INSERT INTO Companies VALUES (1246, 'Sportscene Group Inc.')
INSERT INTO Companies VALUES (1247, 'Sprott Focus Trust, Inc.')
INSERT INTO Companies VALUES (1248, 'SSE plc')
INSERT INTO Companies VALUES (1249, 'SSLJ.com Ltd.')
INSERT INTO Companies VALUES (1250, 'SSP Group plc')
INSERT INTO Companies VALUES (1251, 'St. James House plc')
INSERT INTO Companies VALUES (1252, 'Standard Exploration Ltd.')
INSERT INTO Companies VALUES (1253, 'Star Nutrition, Inc.')
INSERT INTO Companies VALUES (1254, 'Starlight U.S. Multi-Family (No. 5) Core Fund')
INSERT INTO Companies VALUES (1255, 'Start Scientific, Inc.')
INSERT INTO Companies VALUES (1256, 'Start Today Co., Ltd.')
INSERT INTO Companies VALUES (1257, 'State Bank Financial Corp.')
INSERT INTO Companies VALUES (1258, 'STERIS plc')
INSERT INTO Companies VALUES (1259, 'STERIS plc (New)')
INSERT INTO Companies VALUES (1260, 'StillCanna Inc.')
INSERT INTO Companies VALUES (1261, 'Stonecutter Mills Corp.')
INSERT INTO Companies VALUES (1262, 'Strata Oil & Gas Inc.')
INSERT INTO Companies VALUES (1263, 'Strata Power Corp.')
INSERT INTO Companies VALUES (1264, 'Studio City International Holdings Ltd.')
INSERT INTO Companies VALUES (1265, 'Sun Metals Corp.')
INSERT INTO Companies VALUES (1266, 'SunCoke Energy Partners, L.P.')
INSERT INTO Companies VALUES (1267, 'Sunlands Online Education Group')
INSERT INTO Companies VALUES (1268, 'Sunlands Technology Group')
INSERT INTO Companies VALUES (1269, 'Sunshine Biopharma Inc.')
INSERT INTO Companies VALUES (1270, 'SunTrust Banks, Inc.')
INSERT INTO Companies VALUES (1271, 'Sutton Harbour Group plc')
INSERT INTO Companies VALUES (1272, 'Sutton Harbour Holdings plc')
INSERT INTO Companies VALUES (1273, 'Suzano Papel e Celulose SA')
INSERT INTO Companies VALUES (1274, 'Suzano S.A.')
INSERT INTO Companies VALUES (1275, 'Sympowerco Corp.')
INSERT INTO Companies VALUES (1276, 'Synovus Financial Corp.')
INSERT INTO Companies VALUES (1277, 'Synrgy Corp.')
INSERT INTO Companies VALUES (1278, 'Tahoe Resources Inc.')
INSERT INTO Companies VALUES (1279, 'Takeda Pharmaceutical Co. Ltd.')
INSERT INTO Companies VALUES (1280, 'Tanzanian Gold Corp.')
INSERT INTO Companies VALUES (1281, 'Tanzanian Royalty Exploration Corp.')
INSERT INTO Companies VALUES (1282, 'Taptica International Ltd.')
INSERT INTO Companies VALUES (1283, 'Target Hospitality Corp.')
INSERT INTO Companies VALUES (1284, 'Taronis Technologies, Inc.')
INSERT INTO Companies VALUES (1285, 'Tarsus Group plc (New)')
INSERT INTO Companies VALUES (1286, 'Tasca Resources Ltd.')
INSERT INTO Companies VALUES (1287, 'Taseko Mines Ltd.')
INSERT INTO Companies VALUES (1288, 'Tax Systems plc')
INSERT INTO Companies VALUES (1289, 'TC Energy Corp.')
INSERT INTO Companies VALUES (1290, 'TCF Financial Corp.')
INSERT INTO Companies VALUES (1291, 'Tech Leaders Income ETF')
INSERT INTO Companies VALUES (1292, 'Tecnoglass Inc.')
INSERT INTO Companies VALUES (1293, 'Tekla Healthcare Investors')
INSERT INTO Companies VALUES (1294, 'Tekla Life Sciences Investors')
INSERT INTO Companies VALUES (1295, 'Telo Genomics Corp.')
INSERT INTO Companies VALUES (1296, 'Telupay International Inc.')
INSERT INTO Companies VALUES (1297, 'Temple Hotels Inc.')
INSERT INTO Companies VALUES (1298, 'Tencent Holdings Ltd.')
INSERT INTO Companies VALUES (1299, 'Tencent Music Entertainment Group')
INSERT INTO Companies VALUES (1300, 'Tenneco Inc. (2005)')
INSERT INTO Companies VALUES (1301, 'Terumo Corp.')
INSERT INTO Companies VALUES (1302, 'TESARO, Inc.')
INSERT INTO Companies VALUES (1303, 'Tesla, Inc.')
INSERT INTO Companies VALUES (1304, 'Tetragon Financial Group Ltd. ')
INSERT INTO Companies VALUES (1305, 'Teva Pharmaceutical Industries Ltd.')
INSERT INTO Companies VALUES (1306, 'Texas Jack Oil & Gas Corp.')
INSERT INTO Companies VALUES (1307, 'Thales SA')
INSERT INTO Companies VALUES (1308, 'TheStreet, Inc.')
INSERT INTO Companies VALUES (1309, 'Thunder Bridge Acquisition, Ltd.')
INSERT INTO Companies VALUES (1310, 'TIER REIT, Inc.')
INSERT INTO Companies VALUES (1311, 'Tiger Brands Ltd.')
INSERT INTO Companies VALUES (1312, 'TigerShares China-U.S. Internet Titans ETF')
INSERT INTO Companies VALUES (1313, 'Titan Pharmaceuticals, Inc.')
INSERT INTO Companies VALUES (1314, 'Tivity Health, Inc.')
INSERT INTO Companies VALUES (1315, 'TiVo Corp.')
INSERT INTO Companies VALUES (1316, 'Tolima Gold Inc.')
INSERT INTO Companies VALUES (1317, 'Tootsie Roll Industries, Inc.')
INSERT INTO Companies VALUES (1318, 'Top Image Systems Ltd.')
INSERT INTO Companies VALUES (1319, 'TORC Oil & Gas Ltd.')
INSERT INTO Companies VALUES (1320, 'Tortoise Midstream Energy Fund, Inc.')
INSERT INTO Companies VALUES (1321, 'Tortoise MLP Fund, Inc.')
INSERT INTO Companies VALUES (1322, 'Total S.A.')
INSERT INTO Companies VALUES (1323, 'Total System Services, Inc.')
INSERT INTO Companies VALUES (1324, 'Trafalgar Resources, Inc. (UT)')
INSERT INTO Companies VALUES (1325, 'TransCanada Corp.')
INSERT INTO Companies VALUES (1326, 'TransDigm Group Inc.')
INSERT INTO Companies VALUES (1327, 'Trans-Lux Corp.')
INSERT INTO Companies VALUES (1328, 'TransMontaigne Partners L.P.')
INSERT INTO Companies VALUES (1329, 'Travelport Worldwide Ltd.')
INSERT INTO Companies VALUES (1330, 'Tribune Media Co.')
INSERT INTO Companies VALUES (1331, 'Tri-Continental Corp.')
INSERT INTO Companies VALUES (1332, 'Trillion Energy International Inc.')
INSERT INTO Companies VALUES (1333, 'Trinidad Drilling Ltd.')
INSERT INTO Companies VALUES (1334, 'Trinity Capital Corp.')
INSERT INTO Companies VALUES (1335, 'Tritax Big Box REIT plc')
INSERT INTO Companies VALUES (1336, 'Tronox Holdings plc')
INSERT INTO Companies VALUES (1337, 'Tronox Ltd.')
INSERT INTO Companies VALUES (1338, 'TrovaGene, Inc.')
INSERT INTO Companies VALUES (1339, 'True North Gems Inc.')
INSERT INTO Companies VALUES (1340, 'Truett-Hurst, Inc.')
INSERT INTO Companies VALUES (1341, 'TruFin plc')
INSERT INTO Companies VALUES (1342, 'Truli Media Group, Inc. (DE)')
INSERT INTO Companies VALUES (1343, 'Tsim Sha Tsui Properties Ltd.')
INSERT INTO Companies VALUES (1344, 'Tundra Gold Corp.')
INSERT INTO Companies VALUES (1345, 'Twelve Seas Investment Co.')
INSERT INTO Companies VALUES (1346, 'Twenty-First Century Fox, Inc.')
INSERT INTO Companies VALUES (1347, 'Twilio Inc.')
INSERT INTO Companies VALUES (1348, 'Twin River Worldwide Holdings, Inc.')
INSERT INTO Companies VALUES (1349, 'TYG Solutions Corp.')
INSERT INTO Companies VALUES (1350, 'U.S. Well Services, Inc.')
INSERT INTO Companies VALUES (1351, 'uBid Holdings, Inc.')
INSERT INTO Companies VALUES (1352, 'UC Resources Ltd.')
INSERT INTO Companies VALUES (1353, 'Ultimate Software Group, Inc.')
INSERT INTO Companies VALUES (1354, 'Ultrapar Participacoes SA')
INSERT INTO Companies VALUES (1355, 'U-Mind Space, Inc.')
INSERT INTO Companies VALUES (1356, 'Union Acquisition Corp.')
INSERT INTO Companies VALUES (1357, 'Union Bankshares Corp. (New)')
INSERT INTO Companies VALUES (1358, 'Uniserve Communications Corp.')
INSERT INTO Companies VALUES (1359, 'Unite Group plc')
INSERT INTO Companies VALUES (1360, 'Uniti Financial Corp.')
INSERT INTO Companies VALUES (1361, 'Univar Inc.')
INSERT INTO Companies VALUES (1362, 'Universal Copper Ltd.')
INSERT INTO Companies VALUES (1363, 'Univest Corp. of Pennsylvania')
INSERT INTO Companies VALUES (1364, 'Univest Financial Corp.')
INSERT INTO Companies VALUES (1365, 'UP Fintech China-U.S. Internet Titans ETF')
INSERT INTO Companies VALUES (1366, 'UQM Technologies, Inc.')
INSERT INTO Companies VALUES (1367, 'Urban & Civic plc')
INSERT INTO Companies VALUES (1368, 'Urban Select Capital Corp.')
INSERT INTO Companies VALUES (1369, 'Urban Tea, Inc.')
INSERT INTO Companies VALUES (1370, 'uSell.com, Inc.')
INSERT INTO Companies VALUES (1371, 'USG Corp.')
INSERT INTO Companies VALUES (1372, 'Valdor Technology International Inc.')
INSERT INTO Companies VALUES (1373, 'Valencia Ventures Inc.')
INSERT INTO Companies VALUES (1374, 'Valener Inc.')
INSERT INTO Companies VALUES (1375, 'Valeritas Holdings, Inc.')
INSERT INTO Companies VALUES (1376, 'Valero Energy Corp. (New)')
INSERT INTO Companies VALUES (1377, 'Valero Energy Partners LP')
INSERT INTO Companies VALUES (1378, 'ValOro Resources Inc.')
INSERT INTO Companies VALUES (1379, 'VanEck Vectors Generic Drugs ETF ')
INSERT INTO Companies VALUES (1380, 'VanEck Vectors Poland ETF')
INSERT INTO Companies VALUES (1381, 'Vangold Mining Corp.')
INSERT INTO Companies VALUES (1382, 'Vantage Energy Acquisition Corp.')
INSERT INTO Companies VALUES (1383, 'Vectren Corporation')
INSERT INTO Companies VALUES (1384, 'Ventura Cannabis & Wellness Corp.')
INSERT INTO Companies VALUES (1385, 'Venture Vanadium Inc.')
INSERT INTO Companies VALUES (1386, 'Verb Technology Company, Inc.')
INSERT INTO Companies VALUES (1387, 'Veritas Farms, Inc.')
INSERT INTO Companies VALUES (1388, 'Veritas Pharma Inc.')
INSERT INTO Companies VALUES (1389, 'Veritex Holdings, Inc.')
INSERT INTO Companies VALUES (1390, 'Versum Materials, Inc.')
INSERT INTO Companies VALUES (1391, 'VF Corp.')
INSERT INTO Companies VALUES (1392, 'Vibe Bioscience Ltd.')
INSERT INTO Companies VALUES (1393, 'Victory Metals Inc.')
INSERT INTO Companies VALUES (1394, 'Vireo Health International, Inc.')
INSERT INTO Companies VALUES (1395, 'Virginia Community Bankshares, Inc.')
INSERT INTO Companies VALUES (1396, 'Virtu Financial, Inc.')
INSERT INTO Companies VALUES (1397, 'Virtual Crypto Technologies Inc.')
INSERT INTO Companies VALUES (1398, 'Virtus Cumberland Municipal Bond ETF')
INSERT INTO Companies VALUES (1399, 'Vision Plasma Systems, Inc.')
INSERT INTO Companies VALUES (1400, 'Vislink Technologies, Inc.')
INSERT INTO Companies VALUES (1401, 'Vital Therapies, Inc.')
INSERT INTO Companies VALUES (1402, 'VMware, Inc.')
INSERT INTO Companies VALUES (1403, 'Vogogo Inc.')
INSERT INTO Companies VALUES (1404, 'Volcanic Gold Mines Inc.')
INSERT INTO Companies VALUES (1405, 'Vonovia SE')
INSERT INTO Companies VALUES (1406, 'Voyager Digital Canada Ltd.')
INSERT INTO Companies VALUES (1407, 'VuMee, Inc.')
INSERT INTO Companies VALUES (1408, 'WABCO Holdings, Inc.')
INSERT INTO Companies VALUES (1409, 'Wabi Exploration Inc.')
INSERT INTO Companies VALUES (1410, 'Waitr Holdings Inc.')
INSERT INTO Companies VALUES (1411, 'Washington Bancorp, Inc. (WA)')
INSERT INTO Companies VALUES (1412, 'Water Ways Technology Inc.')
INSERT INTO Companies VALUES (1413, 'Wayland Group Corp.')
INSERT INTO Companies VALUES (1414, 'WellCare Health Plans, Inc.')
INSERT INTO Companies VALUES (1415, 'Welltower Inc.')
INSERT INTO Companies VALUES (1416, 'Western Gas Equity Partners, LP')
INSERT INTO Companies VALUES (1417, 'Western Gas Partners, LP')
INSERT INTO Companies VALUES (1418, 'Western Magnesium Corp.')
INSERT INTO Companies VALUES (1419, 'Western Midstream Partners, LP')
INSERT INTO Companies VALUES (1420, 'Western Resources Corp.')
INSERT INTO Companies VALUES (1421, 'Western Sierra Mining Corp.')
INSERT INTO Companies VALUES (1422, 'Western Sierra Resource Corp.')
INSERT INTO Companies VALUES (1423, 'Western Troy Capital Resources Inc.')
INSERT INTO Companies VALUES (1424, 'Westinghouse Air Brake Technologies Corp.')
INSERT INTO Companies VALUES (1425, 'WestJet Airlines Ltd.')
INSERT INTO Companies VALUES (1426, 'Westleaf Inc.')
INSERT INTO Companies VALUES (1427, 'Westmoreland Resource Partners, LP')
INSERT INTO Companies VALUES (1428, 'WestMountain Co.')
INSERT INTO Companies VALUES (1429, 'Westwater Resources, Inc.')
INSERT INTO Companies VALUES (1430, 'WildHorse Resource Development Corp.')
INSERT INTO Companies VALUES (1431, 'William Demant Holding A/S')
INSERT INTO Companies VALUES (1432, 'WillScot Corp.')
INSERT INTO Companies VALUES (1433, 'Windtree Therapeutics, Inc.')
INSERT INTO Companies VALUES (1434, 'Winmark Corporation')
INSERT INTO Companies VALUES (1435, 'Wipro Ltd.')
INSERT INTO Companies VALUES (1436, 'WisdomTree Asia Local Debt Fund')
INSERT INTO Companies VALUES (1437, 'WisdomTree Australia Dividend Fund')
INSERT INTO Companies VALUES (1438, 'WisdomTree Brazilian Real Strategy Fund')
INSERT INTO Companies VALUES (1439, 'WisdomTree Japan Hedged Financials Fund')
INSERT INTO Companies VALUES (1440, 'WisdomTree Japan Hedged Quality Dividend Growth Fund')
INSERT INTO Companies VALUES (1441, 'WisdomTree U.S. Earnings 500 Fund')
INSERT INTO Companies VALUES (1442, 'WisdomTree U.S. LargeCap Fund')
INSERT INTO Companies VALUES (1443, 'WisdomTree U.S. MidCap Earnings Fund')
INSERT INTO Companies VALUES (1444, 'WisdomTree U.S. MidCap Fund')
INSERT INTO Companies VALUES (1445, 'WisdomTree U.S. SmallCap Earnings Fund')
INSERT INTO Companies VALUES (1446, 'WisdomTree U.S. SmallCap Fund')
INSERT INTO Companies VALUES (1447, 'WisdomTree U.S. Total Earnings Fund')
INSERT INTO Companies VALUES (1448, 'WisdomTree U.S. Total Market Fund')
INSERT INTO Companies VALUES (1449, 'Woodbrook Group Holdings, Inc.')
INSERT INTO Companies VALUES (1450, 'Woori Bank')
INSERT INTO Companies VALUES (1451, 'Woori Financial Group Inc.')
INSERT INTO Companies VALUES (1452, 'Workplace Equality Portfolio')
INSERT INTO Companies VALUES (1453, 'Worldline SA')
INSERT INTO Companies VALUES (1454, 'Worldpay, Inc.')
INSERT INTO Companies VALUES (1455, 'Wound Management Technologies, Inc.')
INSERT INTO Companies VALUES (1456, 'WPC Resources Inc.')
INSERT INTO Companies VALUES (1457, 'WSFS Financial Corp.')
INSERT INTO Companies VALUES (1458, 'WU BA Superior Products Holding Group Inc.')
INSERT INTO Companies VALUES (1459, 'Wynnstay Group plc')
INSERT INTO Companies VALUES (1460, 'X4 Pharmaceuticals, Inc.')
INSERT INTO Companies VALUES (1461, 'Xanthic Biopharma Inc.')
INSERT INTO Companies VALUES (1462, 'Xerox Corp.')
INSERT INTO Companies VALUES (1463, 'xG Technology, Inc.')
INSERT INTO Companies VALUES (1464, 'Xiangtian (USA) Air Power Co., Ltd.')
INSERT INTO Companies VALUES (1465, 'Xinliwang International Holdings Company Ltd.')
INSERT INTO Companies VALUES (1466, 'XpresSpa Group, Inc.')
INSERT INTO Companies VALUES (1467, 'XT Energy Group, Inc.')
INSERT INTO Companies VALUES (1468, 'Xtrackers MSCI United Kingdom Hedged Equity ETF')
INSERT INTO Companies VALUES (1469, 'Xynomic Pharmaceuticals Holdings, Inc.')
INSERT INTO Companies VALUES (1470, 'Yaboo, Inc.')
INSERT INTO Companies VALUES (1471, 'YDreams Global Interactive Technologies Inc.')
INSERT INTO Companies VALUES (1472, 'YDx Innovation Corp.')
INSERT INTO Companies VALUES (1473, 'Yellowhead Mining Inc. ')
INSERT INTO Companies VALUES (1474, 'Zadar Ventures Ltd.')
INSERT INTO Companies VALUES (1475, 'Zara Resources Inc.')
INSERT INTO Companies VALUES (1476, 'Zayo Group Holdings, Inc.')
INSERT INTO Companies VALUES (1477, 'ZCL Composites Inc.')
INSERT INTO Companies VALUES (1478, 'Zen Graphene Solutions Ltd.')
INSERT INTO Companies VALUES (1479, 'Zenabis Global Inc.')
INSERT INTO Companies VALUES (1480, 'Zenyatta Ventures Ltd.')
INSERT INTO Companies VALUES (1481, 'Zhongchai Machinery, Inc.')
INSERT INTO Companies VALUES (1482, 'Zovio Inc.')
INSERT INTO Companies VALUES (1483, 'ZOZO, Inc.')
INSERT INTO Companies VALUES (1484, 'ZYQC Group Holding Ltd.')
